import type { ItemDef } from '../types'

export const BCH210_ITEMS: ItemDef[] = [
  // ─── Module 1: Amino Acids & Proteins ────────────────────────────────────────
  // REMEMBER (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-001',
    bloom: 'REMEMBER',
    stem: 'Which of the following amino acids contains a sulfur atom in its side chain?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.75, irtB: -1.2, irtC: 0.22,
    options: [
      { label: 'A', text: 'Serine', justification: 'Serine has a hydroxyl (-OH) side chain, not sulfur.', isCorrect: false },
      { label: 'B', text: 'Cysteine', justification: 'Cysteine has a thiol (-SH) side chain containing sulfur.', isCorrect: true },
      { label: 'C', text: 'Threonine', justification: 'Threonine has a hydroxyl group, not sulfur.', isCorrect: false },
      { label: 'D', text: 'Asparagine', justification: 'Asparagine has an amide side chain with no sulfur.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-002',
    bloom: 'REMEMBER',
    stem: 'What is the general structure shared by all standard amino acids?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.70, irtB: -1.4, irtC: 0.24,
    options: [
      { label: 'A', text: 'A central carbon bonded to an amino group, a carboxyl group, a hydrogen, and a variable R group', justification: 'This is the correct alpha-amino acid backbone.', isCorrect: true },
      { label: 'B', text: 'A central carbon bonded to two amino groups and one carboxyl group', justification: 'Standard amino acids have only one amino group.', isCorrect: false },
      { label: 'C', text: 'A central carbon bonded to an amino group, a phosphate group, and a variable R group', justification: 'Amino acids do not contain a phosphate group.', isCorrect: false },
      { label: 'D', text: 'A central carbon bonded to a carboxyl group, a hydroxyl group, and a variable R group', justification: 'A hydroxyl group does not replace the amino group in standard amino acids.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-003',
    bloom: 'REMEMBER',
    stem: 'Which amino acid is the only one that does not have an L-configuration due to its unique cyclic structure?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.80, irtB: -1.0, irtC: 0.21,
    options: [
      { label: 'A', text: 'Glycine', justification: 'Glycine has no chiral center (two H atoms), but it is not cyclic.', isCorrect: false },
      { label: 'B', text: 'Alanine', justification: 'Alanine is a standard L-amino acid with a methyl side chain.', isCorrect: false },
      { label: 'C', text: 'Proline', justification: 'Proline has a cyclic side chain that connects back to the nitrogen, making it an imino acid with unique structural constraints.', isCorrect: true },
      { label: 'D', text: 'Valine', justification: 'Valine is a standard branched-chain L-amino acid.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-004',
    bloom: 'REMEMBER',
    stem: 'Which of the following amino acids is classified as nonpolar and aromatic?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.72, irtB: -0.9, irtC: 0.23,
    options: [
      { label: 'A', text: 'Tyrosine', justification: 'Tyrosine is aromatic but polar due to its hydroxyl group.', isCorrect: false },
      { label: 'B', text: 'Tryptophan', justification: 'Tryptophan is aromatic but considered mildly polar and can participate in hydrogen bonding via the indole NH.', isCorrect: false },
      { label: 'C', text: 'Phenylalanine', justification: 'Phenylalanine has a benzyl side chain with no polar groups, making it nonpolar aromatic.', isCorrect: true },
      { label: 'D', text: 'Histidine', justification: 'Histidine is aromatic but positively charged/polar at physiological pH.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-005',
    bloom: 'REMEMBER',
    stem: 'What type of bond forms between the carboxyl group of one amino acid and the amino group of another during protein synthesis?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.68, irtB: -1.3, irtC: 0.25,
    options: [
      { label: 'A', text: 'Hydrogen bond', justification: 'Hydrogen bonds stabilize secondary structure but are not the covalent linkage between amino acids.', isCorrect: false },
      { label: 'B', text: 'Disulfide bond', justification: 'Disulfide bonds form between cysteine residues, not between generic amino and carboxyl groups.', isCorrect: false },
      { label: 'C', text: 'Peptide bond', justification: 'A peptide bond (amide bond) forms by condensation between the α-carboxyl and α-amino groups of adjacent residues.', isCorrect: true },
      { label: 'D', text: 'Ionic bond', justification: 'Ionic bonds (salt bridges) can occur between charged side chains but are not the main chain linkage.', isCorrect: false },
    ],
  },
  // UNDERSTAND (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-006',
    bloom: 'UNDERSTAND',
    stem: 'Why does glycine not exhibit optical isomerism?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.95, irtB: -0.6, irtC: 0.20,
    options: [
      { label: 'A', text: 'Its side chain is too small to rotate', justification: 'Optical isomerism depends on chirality, not rotation.', isCorrect: false },
      { label: 'B', text: 'Its alpha-carbon bears two identical hydrogen atoms, so it is not a chiral center', justification: 'With two H atoms, glycine\'s alpha-carbon is achiral, eliminating optical isomers.', isCorrect: true },
      { label: 'C', text: 'It has a cyclic structure that locks it in one configuration', justification: 'It is proline, not glycine, that has a cyclic side chain.', isCorrect: false },
      { label: 'D', text: 'Glycine exists only as a zwitterion at all pH values', justification: 'Zwitterion formation is unrelated to chirality.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-007',
    bloom: 'UNDERSTAND',
    stem: 'What is the significance of the partial double-bond character of the peptide bond?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 1.05, irtB: -0.3, irtC: 0.19,
    options: [
      { label: 'A', text: 'It allows free rotation around the C–N bond, increasing backbone flexibility', justification: 'Partial double-bond character restricts rotation, not increases it.', isCorrect: false },
      { label: 'B', text: 'It makes the peptide bond planar and restricts rotation, limiting backbone conformations', justification: 'Resonance gives the C–N bond ~40% double-bond character, enforcing planarity.', isCorrect: true },
      { label: 'C', text: 'It makes the peptide bond highly reactive toward hydrolysis', justification: 'Partial double-bond character actually stabilizes the bond against hydrolysis somewhat.', isCorrect: false },
      { label: 'D', text: 'It allows cis configurations to predominate in all peptide bonds', justification: 'Trans configurations predominate; only proline frequently adopts cis.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-008',
    bloom: 'UNDERSTAND',
    stem: 'At physiological pH (~7.4), which amino acid side chain carries a positive charge?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 0.90, irtB: -0.5, irtC: 0.21,
    options: [
      { label: 'A', text: 'Aspartate (pKa ~3.9)', justification: 'Aspartate is negatively charged at pH 7.4 because its side chain pKa is far below 7.4.', isCorrect: false },
      { label: 'B', text: 'Lysine (pKa ~10.5)', justification: 'Lysine\'s ε-amino group (pKa ~10.5) is protonated at pH 7.4, giving a positive charge.', isCorrect: true },
      { label: 'C', text: 'Glutamate (pKa ~4.1)', justification: 'Glutamate is negatively charged at pH 7.4.', isCorrect: false },
      { label: 'D', text: 'Asparagine', justification: 'Asparagine is an amide (neutral); it has no ionizable side chain.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-009',
    bloom: 'UNDERSTAND',
    stem: 'What stabilizes the alpha-helical secondary structure of a protein?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.10, irtB: -0.2, irtC: 0.20,
    options: [
      { label: 'A', text: 'Disulfide bonds between cysteine residues', justification: 'Disulfide bonds stabilize tertiary structure, not the alpha-helix specifically.', isCorrect: false },
      { label: 'B', text: 'Hydrogen bonds between backbone carbonyl and NH groups four residues apart', justification: 'In the α-helix, each backbone C=O forms an H-bond with the NH of the residue 4 positions ahead.', isCorrect: true },
      { label: 'C', text: 'Ionic interactions between oppositely charged side chains', justification: 'Salt bridges contribute to tertiary structure stability, not the regular alpha-helix pattern.', isCorrect: false },
      { label: 'D', text: 'Hydrophobic interactions between nonpolar side chains', justification: 'Hydrophobic interactions are key to tertiary structure folding but do not define the alpha-helix.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-010',
    bloom: 'UNDERSTAND',
    stem: 'Which level of protein structure refers to the three-dimensional arrangement of all atoms in a single polypeptide chain?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 0.85, irtB: 0.0, irtC: 0.22,
    options: [
      { label: 'A', text: 'Primary structure', justification: 'Primary structure is the amino acid sequence only.', isCorrect: false },
      { label: 'B', text: 'Secondary structure', justification: 'Secondary structure describes local folding motifs (helix, sheet), not the full 3D arrangement.', isCorrect: false },
      { label: 'C', text: 'Tertiary structure', justification: 'Tertiary structure is the complete 3D fold of a single polypeptide chain including all side-chain interactions.', isCorrect: true },
      { label: 'D', text: 'Quaternary structure', justification: 'Quaternary structure describes the assembly of multiple polypeptide subunits.', isCorrect: false },
    ],
  },
  // APPLY (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-011',
    bloom: 'APPLY',
    stem: 'An amino acid has a pKa of 2.2 for its α-carboxyl group, 9.2 for its α-amino group, and no ionizable side chain. What is its isoelectric point (pI)?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 1.20, irtB: 0.3, irtC: 0.18,
    options: [
      { label: 'A', text: '2.2', justification: 'pI = 2.2 would mean the molecule is at its carboxyl pKa, not the average of the two flanking values.', isCorrect: false },
      { label: 'B', text: '5.7', justification: 'pI = (pKa1 + pKa2)/2 = (2.2 + 9.2)/2 = 5.7, the pH at which the net charge is zero.', isCorrect: true },
      { label: 'C', text: '9.2', justification: 'pI = 9.2 would mean the molecule is at its amino pKa, not their average.', isCorrect: false },
      { label: 'D', text: '7.0', justification: 'pH 7.0 is physiological pH but not the isoelectric point of this amino acid.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-012',
    bloom: 'APPLY',
    stem: 'A peptide has the sequence Ala-Cys-Gly-Cys-Lys. After oxidation, a disulfide bond forms. Which residues are involved?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.15, irtB: 0.5, irtC: 0.20,
    options: [
      { label: 'A', text: 'Ala and Lys', justification: 'Neither alanine nor lysine can form disulfide bonds; they lack thiol groups.', isCorrect: false },
      { label: 'B', text: 'Cys-2 and Cys-4', justification: 'Disulfide bonds form exclusively between cysteine residues via oxidation of their thiol (-SH) groups.', isCorrect: true },
      { label: 'C', text: 'Gly-3 and Lys-5', justification: 'Glycine and lysine do not have thiol groups and cannot form disulfide bonds.', isCorrect: false },
      { label: 'D', text: 'Ala-1 and Gly-3', justification: 'Neither alanine nor glycine has a thiol group required for disulfide bond formation.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-013',
    bloom: 'APPLY',
    stem: 'A researcher uses urea to denature a protein. Which of the following best describes what happens to the protein\'s primary structure?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.10, irtB: 0.4, irtC: 0.19,
    options: [
      { label: 'A', text: 'Peptide bonds are hydrolyzed', justification: 'Urea disrupts non-covalent interactions; it does not break covalent peptide bonds.', isCorrect: false },
      { label: 'B', text: 'The amino acid sequence is scrambled', justification: 'Denaturation does not change the primary sequence; only the folded conformation is disrupted.', isCorrect: false },
      { label: 'C', text: 'The primary structure is unchanged', justification: 'Urea unfolds the protein by disrupting hydrogen bonds and hydrophobic interactions, but the covalent peptide bonds (primary structure) remain intact.', isCorrect: true },
      { label: 'D', text: 'Disulfide bonds are formed', justification: 'Urea denatures proteins; it does not promote disulfide bond formation. Reducing agents like DTT break disulfide bonds.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-014',
    bloom: 'APPLY',
    stem: 'At a pH below its isoelectric point, what is the net charge of an amino acid?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 1.05, irtB: 0.2, irtC: 0.21,
    options: [
      { label: 'A', text: 'Negative', justification: 'Below pI, the solution is more acidic than pI, causing protonation of groups and a net positive charge.', isCorrect: false },
      { label: 'B', text: 'Zero', justification: 'Net charge is zero only at the isoelectric point, not below it.', isCorrect: false },
      { label: 'C', text: 'Positive', justification: 'Below pI, the amino group is protonated (–NH3+) while the carboxyl group tends to be protonated (–COOH), giving a net positive charge.', isCorrect: true },
      { label: 'D', text: 'It depends on the R group only', justification: 'While R groups affect pI, net charge at a given pH is determined by comparing pH to pKa values of all ionizable groups.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-015',
    bloom: 'APPLY',
    stem: 'A protein is found to have its hydrophobic residues largely buried in the interior. What principle explains this arrangement?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.25, irtB: 0.7, irtC: 0.17,
    options: [
      { label: 'A', text: 'The hydrophobic effect drives nonpolar residues away from water', justification: 'Burying hydrophobic residues reduces unfavorable exposure to water, driven by the hydrophobic effect.', isCorrect: true },
      { label: 'B', text: 'Hydrophobic residues are larger and require more space', justification: 'Size alone does not explain burial; electrostatic repulsion from water is the key driver.', isCorrect: false },
      { label: 'C', text: 'Polar residues are too unstable to be in the interior', justification: 'Polar residues can exist in protein interiors, often forming hydrogen bonds with each other.', isCorrect: false },
      { label: 'D', text: 'Hydrophobic residues have higher molecular weights and sink', justification: 'Molecular weight and sinking are not relevant to protein folding thermodynamics.', isCorrect: false },
    ],
  },
  // ANALYZE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-016',
    bloom: 'ANALYZE',
    stem: 'A mutant protein has a valine substituted for a glutamate in the hydrophobic core. What is the most likely effect?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.45, irtB: 0.8, irtC: 0.17,
    options: [
      { label: 'A', text: 'The protein becomes more stable because valine is nonpolar and fits better in the hydrophobic core', justification: 'Glutamate in a hydrophobic core is destabilizing; replacing it with nonpolar valine may actually increase stability.', isCorrect: true },
      { label: 'B', text: 'The protein unfolds immediately because valine is too small', justification: 'Valine is a branched nonpolar residue well-suited to hydrophobic cores; its size is not the issue.', isCorrect: false },
      { label: 'C', text: 'The protein gains a disulfide bond', justification: 'Disulfide bonds require cysteine residues; neither valine nor glutamate are involved.', isCorrect: false },
      { label: 'D', text: 'The pI of the protein shifts to a more basic value because a negative charge is removed', justification: 'This is also plausible, but the question asks for the effect on stability, and removing a buried charge is primarily a stability effect.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-017',
    bloom: 'ANALYZE',
    stem: 'Hemoglobin has four subunits, while myoglobin has only one. Which structural level distinguishes hemoglobin from myoglobin?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 7',
    irtA: 1.35, irtB: 0.9, irtC: 0.18,
    options: [
      { label: 'A', text: 'Primary structure', justification: 'Primary structure (amino acid sequence) differs between the two proteins, but this does not distinguish multi-subunit from single-chain proteins structurally.', isCorrect: false },
      { label: 'B', text: 'Secondary structure', justification: 'Both proteins contain alpha-helices; secondary structure content is similar.', isCorrect: false },
      { label: 'C', text: 'Tertiary structure', justification: 'Both have tertiary structure; the key difference is subunit assembly.', isCorrect: false },
      { label: 'D', text: 'Quaternary structure', justification: 'Quaternary structure describes the arrangement of multiple polypeptide chains; hemoglobin (α2β2) has quaternary structure while myoglobin (single chain) does not.', isCorrect: true },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-018',
    bloom: 'ANALYZE',
    stem: 'In a beta-sheet, which atoms participate in hydrogen bonding to form the sheet structure?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.40, irtB: 1.0, irtC: 0.16,
    options: [
      { label: 'A', text: 'Side-chain R groups of adjacent residues', justification: 'Beta-sheet H-bonds involve backbone atoms, not side chains.', isCorrect: false },
      { label: 'B', text: 'The backbone carbonyl oxygen of one strand and the backbone NH of another strand', justification: 'Beta-sheet hydrogen bonds form between backbone C=O and N–H groups on adjacent parallel or antiparallel strands.', isCorrect: true },
      { label: 'C', text: 'Disulfide bonds between cysteine residues on adjacent strands', justification: 'Disulfide bonds are covalent, not hydrogen bonds, and are not what defines beta-sheet geometry.', isCorrect: false },
      { label: 'D', text: 'Ionic interactions between charged side chains', justification: 'Ionic (salt bridge) interactions occur between side chains but do not define beta-sheet structure.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-019',
    bloom: 'ANALYZE',
    stem: 'A titration curve of histidine shows three pKa values: 1.8, 6.0, and 9.2. Which pKa corresponds to the imidazole side chain?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 1.50, irtB: 1.2, irtC: 0.17,
    options: [
      { label: 'A', text: '1.8', justification: 'pKa 1.8 corresponds to the α-carboxyl group.', isCorrect: false },
      { label: 'B', text: '6.0', justification: 'The imidazole ring of histidine has a pKa near 6.0, making histidine important in enzyme active sites near physiological pH.', isCorrect: true },
      { label: 'C', text: '9.2', justification: 'pKa 9.2 corresponds to the α-amino group of histidine.', isCorrect: false },
      { label: 'D', text: 'All three pKa values correspond to the imidazole', justification: 'Each pKa value corresponds to one ionizable group; only one is the imidazole.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-020',
    bloom: 'ANALYZE',
    stem: 'Collagen contains a high proportion of glycine, proline, and hydroxyproline. What structural feature do these residues help create?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.55, irtB: 1.1, irtC: 0.16,
    options: [
      { label: 'A', text: 'A beta-barrel with hydrophobic core', justification: 'Collagen does not form a beta-barrel; that structure is found in membrane proteins.', isCorrect: false },
      { label: 'B', text: 'A triple helix with glycine at every third position fitting the center', justification: 'Collagen\'s repeating Gly-X-Y sequence allows glycine (smallest) to occupy the inner core of the triple helix; Pro and HyPro stabilize the helix via steric and H-bonding effects.', isCorrect: true },
      { label: 'C', text: 'An alpha-helix stabilized by hydrophobic packing', justification: 'Proline is a helix breaker; collagen does not adopt a standard alpha-helix.', isCorrect: false },
      { label: 'D', text: 'A random coil for flexibility', justification: 'Collagen is highly ordered; its triple helix provides structural rigidity, not random flexibility.', isCorrect: false },
    ],
  },
  // EVALUATE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-021',
    bloom: 'EVALUATE',
    stem: 'A student claims that all proteins will refold spontaneously to their native structure after denaturation in any conditions. Evaluate this claim.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.60, irtB: 1.3, irtC: 0.16,
    options: [
      { label: 'A', text: 'The claim is correct; Anfinsen\'s experiment proves all proteins refold spontaneously', justification: 'Anfinsen showed RNase A refolded in vitro, but this does not apply universally to all proteins.', isCorrect: false },
      { label: 'B', text: 'The claim is partially correct; small soluble proteins may refold spontaneously, but large or complex proteins often require chaperones in vivo', justification: 'Anfinsen\'s thermodynamic hypothesis holds that the native state is the global free energy minimum, but many proteins need chaperones to avoid misfolding/aggregation.', isCorrect: true },
      { label: 'C', text: 'The claim is incorrect; no protein can ever refold after denaturation', justification: 'This is too absolute; Anfinsen\'s ribonuclease A experiment showed spontaneous refolding in vitro.', isCorrect: false },
      { label: 'D', text: 'The claim is irrelevant because proteins are always newly synthesized rather than refolded', justification: 'Refolding does occur in vivo and is studied in vitro; this response misses the thermodynamic question.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-022',
    bloom: 'EVALUATE',
    stem: 'Two variants of a structural protein are proposed: one with more proline residues, one with fewer. Which would you predict to form more rigid fibers, and why?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.65, irtB: 1.4, irtC: 0.15,
    options: [
      { label: 'A', text: 'The one with fewer proline residues, because proline destabilizes all structures', justification: 'Proline restricts backbone flexibility but can stabilize specific structures like the collagen triple helix.', isCorrect: false },
      { label: 'B', text: 'The one with more proline residues, because proline restricts backbone phi angles, reducing conformational flexibility', justification: 'Proline\'s cyclic side chain limits backbone dihedral angles, introducing rigidity that is exploited in structural proteins like collagen.', isCorrect: true },
      { label: 'C', text: 'Both variants would have equal rigidity because rigidity depends only on disulfide bonds', justification: 'While disulfide bonds contribute to stability, backbone conformational flexibility (affected by proline) is also a major determinant of rigidity.', isCorrect: false },
      { label: 'D', text: 'Rigidity cannot be predicted from amino acid composition alone', justification: 'While context matters, proline content is a well-established predictor of backbone rigidity.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-023',
    bloom: 'EVALUATE',
    stem: 'A new drug is designed to reduce a disulfide bond in a pathogenic protein, causing it to unfold. Which reducing agent would be most appropriate?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.55, irtB: 1.1, irtC: 0.16,
    options: [
      { label: 'A', text: 'Urea', justification: 'Urea is a chaotropic agent that disrupts non-covalent bonds, not covalent disulfide bonds.', isCorrect: false },
      { label: 'B', text: 'Dithiothreitol (DTT)', justification: 'DTT is a reducing agent that cleaves disulfide bonds by donating electrons, converting S–S to two –SH groups.', isCorrect: true },
      { label: 'C', text: 'SDS', justification: 'SDS (sodium dodecyl sulfate) is a detergent that disrupts hydrophobic interactions, not disulfide bonds.', isCorrect: false },
      { label: 'D', text: 'Hydrogen peroxide', justification: 'Hydrogen peroxide is an oxidizing agent and would actually promote disulfide bond formation, not reduction.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-024',
    bloom: 'EVALUATE',
    stem: 'Sickle cell anemia results from a single amino acid change in hemoglobin (Glu6Val in the beta-chain). What does this teach us about protein structure-function relationships?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 7',
    irtA: 1.70, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Only large structural changes in the primary sequence affect function', justification: 'Sickle cell disease demonstrates that even a single amino acid substitution can be catastrophically destabilizing.', isCorrect: false },
      { label: 'B', text: 'A single conservative amino acid substitution never affects function', justification: 'Glu→Val is a nonconservative substitution (charged to nonpolar), and it profoundly affects function.', isCorrect: false },
      { label: 'C', text: 'Even a single nonconservative amino acid change can drastically alter protein function by changing surface properties', justification: 'Replacing charged Glu with nonpolar Val creates a hydrophobic patch, causing polymerization of deoxy-HbS and fiber formation.', isCorrect: true },
      { label: 'D', text: 'The primary structure is unimportant because tertiary structure determines function', justification: 'Primary structure encodes tertiary structure; they are inseparable in determining function.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-025',
    bloom: 'EVALUATE',
    stem: 'Which experimental approach would best determine if a newly discovered protein forms a homodimer?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.65, irtB: 1.3, irtC: 0.15,
    options: [
      { label: 'A', text: 'SDS-PAGE under denaturing conditions', justification: 'SDS-PAGE denatures and separates subunits, showing monomer mass but not native oligomeric state.', isCorrect: false },
      { label: 'B', text: 'Amino acid sequencing', justification: 'Sequencing reveals the primary structure but not whether two identical chains associate.', isCorrect: false },
      { label: 'C', text: 'Native PAGE or size exclusion chromatography (SEC) combined with analytical ultracentrifugation', justification: 'These techniques measure the native molecular mass and hydrodynamic properties, allowing determination of oligomeric state without denaturation.', isCorrect: true },
      { label: 'D', text: 'Circular dichroism spectroscopy', justification: 'CD measures secondary structure content (alpha-helix, beta-sheet) but cannot determine quaternary assembly.', isCorrect: false },
    ],
  },
  // CREATE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-026',
    bloom: 'CREATE',
    stem: 'You are designing a peptide that must: (1) be positively charged at pH 7, (2) form an alpha-helix, and (3) have one disulfide bond capability. Which combination of amino acid properties should you incorporate?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2-3',
    irtA: 1.80, irtB: 1.6, irtC: 0.15,
    options: [
      { label: 'A', text: 'Include lysine or arginine for positive charge, alanine for helix propensity, and cysteine for disulfide', justification: 'Lys/Arg are positively charged at pH 7; alanine has the highest alpha-helix propensity; cysteine provides the thiol for disulfide bond formation.', isCorrect: true },
      { label: 'B', text: 'Include aspartate for positive charge, proline for helix formation, and serine for disulfide', justification: 'Aspartate is negatively charged at pH 7; proline is a helix breaker; serine cannot form disulfide bonds.', isCorrect: false },
      { label: 'C', text: 'Include glutamate for positive charge, glycine for helix formation, and methionine for disulfide', justification: 'Glutamate is negatively charged; glycine destabilizes helices; methionine has no free thiol for disulfide bonds.', isCorrect: false },
      { label: 'D', text: 'Include histidine for positive charge, isoleucine for helix formation, and tyrosine for disulfide', justification: 'Histidine is only ~50% protonated at pH 7; isoleucine has moderate helix propensity; tyrosine cannot form disulfide bonds.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-027',
    bloom: 'CREATE',
    stem: 'A biochemist wants to engineer a thermostable version of a mesophilic enzyme. Which structural modifications would most increase thermal stability?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.75, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Replace surface lysines with arginines and add disulfide bonds in the core', justification: 'Arginine forms more stabilizing interactions; additional disulfide bonds covalently constrain the fold, both increasing thermal stability.', isCorrect: true },
      { label: 'B', text: 'Replace all hydrophobic residues with polar ones to increase solubility', justification: 'Removing the hydrophobic core would destabilize the protein, not increase thermal stability.', isCorrect: false },
      { label: 'C', text: 'Increase the number of glycine residues for backbone flexibility', justification: 'More glycine increases flexibility and entropy of the unfolded state, generally reducing thermal stability.', isCorrect: false },
      { label: 'D', text: 'Replace all cysteines with serines to prevent aggregation', justification: 'Removing cysteines eliminates disulfide bond potential, typically reducing stability.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-028',
    bloom: 'CREATE',
    stem: 'You want to create a fluorescent probe that covalently labels only free thiol groups in a protein at physiological pH. Which chemical functionality should the probe contain?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 2',
    irtA: 1.85, irtB: 1.7, irtC: 0.15,
    options: [
      { label: 'A', text: 'A maleimide group', justification: 'Maleimide groups react specifically and efficiently with free thiols (–SH of cysteine) at pH 6.5–7.5, making them ideal for selective cysteine labeling.', isCorrect: true },
      { label: 'B', text: 'An NHS ester group', justification: 'NHS esters react with primary amines (lysine, N-terminus), not thiols.', isCorrect: false },
      { label: 'C', text: 'A boronic acid group', justification: 'Boronic acids react with diols (sugars), not specifically with thiols.', isCorrect: false },
      { label: 'D', text: 'An aldehyde group', justification: 'Aldehydes react with amines to form Schiff bases, not with thiols preferentially.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-029',
    bloom: 'CREATE',
    stem: 'Design an experiment to determine whether a protein\'s tertiary structure is maintained by hydrophobic interactions or primarily by disulfide bonds.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.90, irtB: 1.8, irtC: 0.15,
    options: [
      { label: 'A', text: 'Treat the protein with urea alone (disrupts H-bonds and hydrophobic interactions) vs. DTT alone (reduces disulfide bonds); observe which causes unfolding', justification: 'Urea disrupts non-covalent interactions including hydrophobic effects; DTT specifically reduces disulfide bonds. Comparing these treatments reveals the dominant stabilizing force.', isCorrect: true },
      { label: 'B', text: 'Run SDS-PAGE under native conditions and check molecular weight', justification: 'Native PAGE preserves structure but does not distinguish between disulfide and hydrophobic stabilization.', isCorrect: false },
      { label: 'C', text: 'Sequence the protein to count cysteines', justification: 'Counting cysteines tells you the potential for disulfide bonds but not which force actually stabilizes the structure.', isCorrect: false },
      { label: 'D', text: 'Measure UV absorbance at 280 nm', justification: 'A280 measures aromatic residue content (Trp, Tyr) but cannot distinguish stabilizing forces.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Amino Acids & Proteins',
    externalQuestionId: 'BCH210-AA-030',
    bloom: 'CREATE',
    stem: 'You are proposing a new protein-based biomaterial that must self-assemble into fibers at body temperature. Which naturally occurring protein would be your best model and why?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 3',
    irtA: 1.95, irtB: 1.9, irtC: 0.15,
    options: [
      { label: 'A', text: 'Collagen, because it forms triple-helical fibers stabilized by Gly-X-Y repeats and hydroxyproline hydrogen bonding', justification: 'Collagen is the quintessential self-assembling structural protein, forming fibers through triple-helix association, making it an ideal biomaterial model.', isCorrect: true },
      { label: 'B', text: 'Myoglobin, because it has a compact globular fold', justification: 'Myoglobin is a globular oxygen-storage protein and does not self-assemble into fibers.', isCorrect: false },
      { label: 'C', text: 'Insulin, because it is a small soluble peptide hormone', justification: 'Insulin does not form self-assembled fibers under physiological conditions.', isCorrect: false },
      { label: 'D', text: 'Casein, because it forms micelles in milk', justification: 'Casein micelles form in aqueous solution but are not the structural protein fiber model sought here.', isCorrect: false },
    ],
  },

  // ─── Module 2: Enzyme Kinetics ────────────────────────────────────────────────
  // REMEMBER (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-001',
    bloom: 'REMEMBER',
    stem: 'What does the Michaelis constant (Km) represent?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.78, irtB: -1.1, irtC: 0.23,
    options: [
      { label: 'A', text: 'The maximum reaction velocity', justification: 'Vmax is the maximum velocity; Km is a concentration, not a rate.', isCorrect: false },
      { label: 'B', text: 'The substrate concentration at which reaction velocity is half of Vmax', justification: 'By definition, Km = [S] when v = Vmax/2; it reflects the enzyme\'s affinity for the substrate.', isCorrect: true },
      { label: 'C', text: 'The concentration of enzyme required for half-maximal activity', justification: 'Km is a substrate concentration, not an enzyme concentration.', isCorrect: false },
      { label: 'D', text: 'The equilibrium constant of the enzyme-substrate complex formation', justification: 'Km is not the equilibrium constant; it is a composite of rate constants (k-1 + kcat)/k1.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-002',
    bloom: 'REMEMBER',
    stem: 'Which of the following is a characteristic of a competitive inhibitor?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.82, irtB: -0.9, irtC: 0.21,
    options: [
      { label: 'A', text: 'It decreases Vmax and increases Km', justification: 'This describes noncompetitive inhibition, not competitive inhibition.', isCorrect: false },
      { label: 'B', text: 'It increases apparent Km but does not change Vmax', justification: 'A competitive inhibitor competes with substrate for the active site; increasing substrate concentration can overcome inhibition, so Vmax is unchanged but Km appears higher.', isCorrect: true },
      { label: 'C', text: 'It binds only to the enzyme-substrate complex', justification: 'This describes an uncompetitive inhibitor, which binds the ES complex.', isCorrect: false },
      { label: 'D', text: 'It irreversibly modifies the active site residue', justification: 'Irreversible inhibition is a separate category; competitive inhibitors bind reversibly at the active site.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-003',
    bloom: 'REMEMBER',
    stem: 'What is the catalytic constant (kcat) also known as?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.70, irtB: -1.0, irtC: 0.24,
    options: [
      { label: 'A', text: 'The Michaelis constant', justification: 'The Michaelis constant is Km, not kcat.', isCorrect: false },
      { label: 'B', text: 'The turnover number', justification: 'kcat, or turnover number, is the number of substrate molecules converted to product per enzyme active site per unit time at saturating substrate.', isCorrect: true },
      { label: 'C', text: 'The dissociation constant', justification: 'The dissociation constant (Ks) describes binding affinity; kcat describes catalytic rate.', isCorrect: false },
      { label: 'D', text: 'The inhibition constant', justification: 'The inhibition constant is Ki; kcat is the turnover number.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-004',
    bloom: 'REMEMBER',
    stem: 'In a Lineweaver-Burk (double-reciprocal) plot, what does the y-intercept represent?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.75, irtB: -0.8, irtC: 0.22,
    options: [
      { label: 'A', text: '–1/Km', justification: '–1/Km is the x-intercept of the Lineweaver-Burk plot.', isCorrect: false },
      { label: 'B', text: '1/Vmax', justification: 'The y-intercept (where 1/[S] = 0, i.e., [S] → ∞) equals 1/Vmax.', isCorrect: true },
      { label: 'C', text: 'Km/Vmax', justification: 'Km/Vmax is the slope of the Lineweaver-Burk plot, not the y-intercept.', isCorrect: false },
      { label: 'D', text: 'Vmax', justification: 'Vmax is the reciprocal of the y-intercept, not the y-intercept itself.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-005',
    bloom: 'REMEMBER',
    stem: 'Which of the following best describes an allosteric enzyme?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 10',
    irtA: 0.80, irtB: -0.7, irtC: 0.20,
    options: [
      { label: 'A', text: 'An enzyme whose activity is regulated by pH changes only', justification: 'Allosteric regulation involves effector molecule binding, not just pH changes.', isCorrect: false },
      { label: 'B', text: 'An enzyme that has a single active site and no regulatory subunits', justification: 'Allosteric enzymes typically have multiple subunits and regulatory sites distinct from the active site.', isCorrect: false },
      { label: 'C', text: 'An enzyme that has a regulatory site distinct from its active site where effectors bind to modulate activity', justification: 'Allosteric regulation occurs through conformational changes induced by effector binding at a site other than the active site.', isCorrect: true },
      { label: 'D', text: 'An enzyme that requires a cofactor for every catalytic cycle', justification: 'Cofactor dependence is not the defining feature of allosteric regulation.', isCorrect: false },
    ],
  },
  // UNDERSTAND (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-006',
    bloom: 'UNDERSTAND',
    stem: 'Why does increasing substrate concentration eventually fail to increase reaction velocity beyond Vmax?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.95, irtB: -0.4, irtC: 0.19,
    options: [
      { label: 'A', text: 'Excess substrate inhibits the enzyme by blocking the active site', justification: 'While substrate inhibition can occur at very high concentrations in some enzymes, the general explanation for the Vmax plateau is enzyme saturation.', isCorrect: false },
      { label: 'B', text: 'All enzyme active sites are occupied (saturated) and the rate is limited by the catalytic step', justification: 'At Vmax, every enzyme molecule has substrate bound; increasing [S] further cannot increase the rate because there are no free active sites.', isCorrect: true },
      { label: 'C', text: 'The substrate begins to denature at high concentrations', justification: 'Substrate denaturation is not the reason for the Vmax plateau under normal conditions.', isCorrect: false },
      { label: 'D', text: 'The product accumulates and inhibits the reaction by mass action', justification: 'While product inhibition can occur, the Michaelis-Menten model assumes [P] ≈ 0 (initial velocity conditions).', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-007',
    bloom: 'UNDERSTAND',
    stem: 'How does a noncompetitive inhibitor differ from a competitive inhibitor in its effect on Km and Vmax?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.05, irtB: -0.2, irtC: 0.21,
    options: [
      { label: 'A', text: 'Noncompetitive inhibition increases Km; competitive inhibition decreases Vmax', justification: 'This is the opposite of the correct relationship.', isCorrect: false },
      { label: 'B', text: 'Noncompetitive inhibition decreases Vmax without affecting Km; competitive inhibition increases Km without affecting Vmax', justification: 'A noncompetitive inhibitor binds equally to E and ES, reducing Vmax but not affecting apparent Km; competitive inhibitor increases apparent Km but Vmax is unchanged.', isCorrect: true },
      { label: 'C', text: 'Both types decrease Vmax but have no effect on Km', justification: 'Competitive inhibition increases Km; it does not decrease Vmax.', isCorrect: false },
      { label: 'D', text: 'Noncompetitive inhibition increases Km and decreases Vmax simultaneously', justification: 'This would describe mixed inhibition, not pure noncompetitive inhibition.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-008',
    bloom: 'UNDERSTAND',
    stem: 'What is the physical meaning of a low Km value for an enzyme?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 0.90, irtB: -0.3, irtC: 0.20,
    options: [
      { label: 'A', text: 'The enzyme requires a high concentration of substrate to function', justification: 'High Km (not low) indicates the enzyme needs more substrate to reach half-maximal velocity.', isCorrect: false },
      { label: 'B', text: 'The enzyme has a high affinity for its substrate', justification: 'Low Km means the enzyme reaches half-maximal velocity at low [S], indicating high affinity.', isCorrect: true },
      { label: 'C', text: 'The enzyme has a high turnover number', justification: 'kcat (turnover number) describes catalytic rate; Km describes affinity.', isCorrect: false },
      { label: 'D', text: 'The enzyme is inhibited at low substrate concentrations', justification: 'Low Km indicates the enzyme works well at low substrate, not that it is inhibited.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-009',
    bloom: 'UNDERSTAND',
    stem: 'In the Michaelis-Menten model, what is the significance of the steady-state assumption?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.10, irtB: 0.1, irtC: 0.19,
    options: [
      { label: 'A', text: 'The rate of substrate binding equals the rate of product release', justification: 'The steady state refers to [ES] being constant, not specifically to binding equaling product release.', isCorrect: false },
      { label: 'B', text: 'The concentration of the enzyme-substrate complex (ES) remains constant because the rates of its formation and breakdown are equal', justification: 'Steady-state means d[ES]/dt ≈ 0, allowing derivation of the Michaelis-Menten equation.', isCorrect: true },
      { label: 'C', text: 'The total enzyme concentration equals the substrate concentration', justification: 'The model assumes [E]total << [S], but this is not the steady-state assumption itself.', isCorrect: false },
      { label: 'D', text: 'The reaction has reached equilibrium', justification: 'The steady-state assumption is applied far from equilibrium, under initial rate conditions.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-010',
    bloom: 'UNDERSTAND',
    stem: 'Why is the ratio kcat/Km (catalytic efficiency) a useful parameter for comparing enzymes?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.15, irtB: 0.2, irtC: 0.18,
    options: [
      { label: 'A', text: 'It measures the enzyme\'s maximum possible rate at saturating substrate', justification: 'kcat alone measures maximum rate at saturation; kcat/Km is meaningful at low [S].', isCorrect: false },
      { label: 'B', text: 'It represents the second-order rate constant for the reaction of free enzyme with free substrate, combining affinity and catalytic rate', justification: 'kcat/Km is the apparent second-order rate constant for E + S → E + P at low [S], reflecting both binding and catalysis.', isCorrect: true },
      { label: 'C', text: 'It gives the exact equilibrium constant for substrate binding', justification: 'Km is not the equilibrium constant; kcat/Km is a rate constant, not an equilibrium constant.', isCorrect: false },
      { label: 'D', text: 'It is independent of enzyme concentration', justification: 'All Michaelis-Menten parameters are measured per enzyme molecule and are defined at specific [E]total.', isCorrect: false },
    ],
  },
  // APPLY (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-011',
    bloom: 'APPLY',
    stem: 'An enzyme has Km = 2 mM and Vmax = 100 μmol/min. What is the reaction velocity when [S] = 2 mM?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.30, irtB: 0.4, irtC: 0.18,
    options: [
      { label: 'A', text: '25 μmol/min', justification: 'v = Vmax[S]/(Km+[S]) = 100×2/(2+2) = 50 μmol/min, not 25.', isCorrect: false },
      { label: 'B', text: '50 μmol/min', justification: 'When [S] = Km, v = Vmax/2 = 100/2 = 50 μmol/min by definition of Km.', isCorrect: true },
      { label: 'C', text: '100 μmol/min', justification: '100 μmol/min is Vmax, achieved only at infinitely high [S].', isCorrect: false },
      { label: 'D', text: '75 μmol/min', justification: 'v = 75 μmol/min would require [S] = 3Km = 6 mM, not 2 mM.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-012',
    bloom: 'APPLY',
    stem: 'You add a competitive inhibitor to an enzyme assay. Which change would restore the original reaction velocity?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.20, irtB: 0.5, irtC: 0.20,
    options: [
      { label: 'A', text: 'Decreasing substrate concentration', justification: 'Decreasing [S] would worsen the inhibition by reducing competition for active sites.', isCorrect: false },
      { label: 'B', text: 'Increasing substrate concentration to outcompete the inhibitor', justification: 'Competitive inhibition is reversible and can be overcome by increasing [S]; at sufficiently high [S], the enzyme can achieve Vmax as if no inhibitor were present.', isCorrect: true },
      { label: 'C', text: 'Adding a reducing agent like DTT', justification: 'DTT reduces disulfide bonds; it would not specifically reverse competitive inhibition.', isCorrect: false },
      { label: 'D', text: 'Lowering the pH to protonate the inhibitor', justification: 'While pH changes affect enzyme activity, lowering pH is not the primary way to reverse competitive inhibition.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-013',
    bloom: 'APPLY',
    stem: 'On a Lineweaver-Burk plot, you observe that adding inhibitor X increases the slope but does not change the y-intercept. What type of inhibitor is X?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.35, irtB: 0.7, irtC: 0.19,
    options: [
      { label: 'A', text: 'Noncompetitive inhibitor', justification: 'A noncompetitive inhibitor changes both the slope and the y-intercept (decreasing Vmax, same Km).', isCorrect: false },
      { label: 'B', text: 'Competitive inhibitor', justification: 'A competitive inhibitor increases the slope (increases Km) without changing the y-intercept (Vmax unchanged), exactly as described.', isCorrect: true },
      { label: 'C', text: 'Uncompetitive inhibitor', justification: 'An uncompetitive inhibitor decreases both Km and Vmax, shifting the line downward in parallel on a Lineweaver-Burk plot.', isCorrect: false },
      { label: 'D', text: 'Irreversible inhibitor', justification: 'Irreversible inhibitors reduce the amount of active enzyme, reducing Vmax; they would change the y-intercept.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-014',
    bloom: 'APPLY',
    stem: 'Enzyme A has kcat = 1000 s⁻¹ and Km = 0.1 mM. Enzyme B has kcat = 100 s⁻¹ and Km = 0.001 mM. At very low substrate concentrations, which enzyme is more efficient?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.40, irtB: 0.8, irtC: 0.17,
    options: [
      { label: 'A', text: 'Enzyme A, because it has a higher kcat', justification: 'At low [S], kcat alone does not determine efficiency; kcat/Km does.', isCorrect: false },
      { label: 'B', text: 'Enzyme B, because kcat/Km = 100/(0.001×10⁻³) = 10⁸ M⁻¹s⁻¹, much higher than Enzyme A\'s 10⁷ M⁻¹s⁻¹', justification: 'At low [S], catalytic efficiency is kcat/Km. Enzyme B: 100/(10⁻⁶) = 10⁸ M⁻¹s⁻¹; Enzyme A: 1000/(10⁻⁴) = 10⁷ M⁻¹s⁻¹. Enzyme B wins.', isCorrect: true },
      { label: 'C', text: 'Enzyme A and B are equally efficient because neither is saturated', justification: 'Their kcat/Km values differ by 10-fold; they are not equally efficient.', isCorrect: false },
      { label: 'D', text: 'Enzyme B is less efficient because it has a lower kcat', justification: 'kcat alone does not determine low-[S] efficiency; the ratio kcat/Km is the correct measure.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-015',
    bloom: 'APPLY',
    stem: 'Aspirin irreversibly inhibits cyclooxygenase by acetylating a serine in the active site. Which kinetic parameter is most directly affected?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.25, irtB: 0.6, irtC: 0.19,
    options: [
      { label: 'A', text: 'Km increases because substrate cannot bind as tightly', justification: 'Irreversible inhibition reduces functional enzyme concentration; it does not change Km for the remaining active enzyme.', isCorrect: false },
      { label: 'B', text: 'Vmax decreases because fewer functional enzyme molecules are available', justification: 'Irreversible inhibition permanently inactivates enzyme molecules, reducing the total functional [E]total and thus Vmax proportionally.', isCorrect: true },
      { label: 'C', text: 'kcat increases because the modified enzyme is hyperactivated', justification: 'Acetylation blocks catalysis; it does not increase kcat.', isCorrect: false },
      { label: 'D', text: 'Km decreases because the inhibitor helps align the substrate', justification: 'Irreversible inhibition does not enhance substrate binding in remaining functional enzyme.', isCorrect: false },
    ],
  },
  // ANALYZE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-016',
    bloom: 'ANALYZE',
    stem: 'Phosphofructokinase-1 (PFK-1) is inhibited by ATP and activated by AMP. What does this regulation reveal about PFK-1\'s role in metabolism?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 16',
    irtA: 1.50, irtB: 1.0, irtC: 0.16,
    options: [
      { label: 'A', text: 'PFK-1 is a biosynthetic enzyme that should be active when ATP is high', justification: 'PFK-1 is a glycolytic enzyme; ATP inhibition makes sense for a catabolic pathway (glycolysis) that would be wasteful if the cell already has high ATP.', isCorrect: false },
      { label: 'B', text: 'PFK-1 is a key regulated step in glycolysis, sensitive to the cellular energy charge, slowing glycolysis when ATP is abundant and accelerating it when energy is low (high AMP)', justification: 'PFK-1 acts as an energy sensor: high ATP (cell energy-replete) inhibits it; high AMP (cell energy-depleted) activates it, coupling glycolytic flux to energy demand.', isCorrect: true },
      { label: 'C', text: 'PFK-1 activity is irrelevant to the cell\'s energy status', justification: 'PFK-1 is a major control point of glycolysis and is exquisitely sensitive to energy status.', isCorrect: false },
      { label: 'D', text: 'ATP activation of PFK-1 ensures that glycolysis always runs at maximum rate', justification: 'ATP inhibits (not activates) PFK-1; this prevents wasteful glycolysis when ATP is plentiful.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-017',
    bloom: 'ANALYZE',
    stem: 'An enzyme shows a sigmoidal V vs. [S] curve rather than a hyperbolic one. What does this indicate?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 10',
    irtA: 1.45, irtB: 0.9, irtC: 0.17,
    options: [
      { label: 'A', text: 'The enzyme follows simple Michaelis-Menten kinetics', justification: 'Michaelis-Menten kinetics produces a hyperbolic curve; sigmoidal curves indicate cooperative behavior.', isCorrect: false },
      { label: 'B', text: 'The enzyme displays positive cooperativity, where binding of one substrate molecule increases the affinity of subsequent binding events', justification: 'Sigmoidal kinetics is the hallmark of cooperative enzymes (e.g., hemoglobin for O2, aspartate transcarbamoylase); binding of substrate to one subunit enhances binding to others.', isCorrect: true },
      { label: 'C', text: 'The enzyme is subject to product inhibition', justification: 'Product inhibition would modify the Michaelis-Menten curve but would not inherently create a sigmoidal shape.', isCorrect: false },
      { label: 'D', text: 'The enzyme has multiple competing substrates', justification: 'Multiple substrates would produce more complex kinetics but not a simple sigmoidal curve.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-018',
    bloom: 'ANALYZE',
    stem: 'Enzyme kinetics data in the presence of inhibitor shows both the slope and y-intercept of the Lineweaver-Burk plot change (increase), but the x-intercept does not change. What type of inhibition is this?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.55, irtB: 1.1, irtC: 0.16,
    options: [
      { label: 'A', text: 'Competitive inhibition', justification: 'Competitive inhibition changes the slope and x-intercept but not the y-intercept.', isCorrect: false },
      { label: 'B', text: 'Noncompetitive inhibition', justification: 'Noncompetitive inhibition changes the y-intercept (and slope) but not the x-intercept (Km is unchanged). This matches the description.', isCorrect: true },
      { label: 'C', text: 'Uncompetitive inhibition', justification: 'Uncompetitive inhibition produces parallel lines (same slope, different intercepts).', isCorrect: false },
      { label: 'D', text: 'Substrate inhibition', justification: 'Substrate inhibition is seen at very high [S] and produces curved Lineweaver-Burk plots, not a simple shifted line.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-019',
    bloom: 'ANALYZE',
    stem: 'Feedback inhibition of an allosteric enzyme by its pathway\'s end product is a key metabolic control mechanism. Why is this advantageous compared to simply reducing enzyme gene expression?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 10',
    irtA: 1.60, irtB: 1.3, irtC: 0.15,
    options: [
      { label: 'A', text: 'Allosteric inhibition is slower but more permanent', justification: 'Allosteric inhibition is actually faster (seconds) than transcriptional regulation (minutes to hours).', isCorrect: false },
      { label: 'B', text: 'Allosteric feedback allows rapid, reversible, concentration-sensitive modulation without altering enzyme levels', justification: 'Allosteric inhibition is nearly instantaneous, reversible when product levels drop, and proportional to product concentration—far faster and more fine-tuned than gene regulation.', isCorrect: true },
      { label: 'C', text: 'Gene expression control is always faster than allosteric inhibition', justification: 'The opposite is true; gene expression changes take minutes to hours whereas allosteric inhibition acts in milliseconds to seconds.', isCorrect: false },
      { label: 'D', text: 'Allosteric inhibition is used only in catabolic pathways', justification: 'Allosteric feedback inhibition is common in both biosynthetic (anabolic) pathways, such as amino acid synthesis, and catabolic pathways.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-020',
    bloom: 'ANALYZE',
    stem: 'A drug (a transition-state analog) has Ki = 10⁻¹⁰ M while the natural substrate has Km = 10⁻³ M. What does this difference imply?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.65, irtB: 1.2, irtC: 0.16,
    options: [
      { label: 'A', text: 'The drug is weaker than the substrate because its Ki is smaller', justification: 'A smaller Ki means tighter binding (higher affinity), not weaker binding.', isCorrect: false },
      { label: 'B', text: 'The enzyme binds the transition-state analog ~10⁷-fold more tightly than the substrate, illustrating why enzymes are excellent catalysts (they complement transition states)', justification: 'Ki/Km = 10⁻¹⁰/10⁻³ = 10⁻⁷, meaning the analog binds 10⁷-fold tighter. This reflects the catalytic power of enzymes: they are evolved to bind transition states far more tightly than substrates.', isCorrect: true },
      { label: 'C', text: 'The drug will competitively inhibit the enzyme but the substrate will rapidly displace it', justification: 'With Ki 10⁷-fold lower than Km, the substrate cannot easily displace the analog.', isCorrect: false },
      { label: 'D', text: 'Both the drug and substrate bind the enzyme with equal affinity under physiological conditions', justification: 'Their affinities differ by 10 million-fold; they are far from equal.', isCorrect: false },
    ],
  },
  // EVALUATE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-021',
    bloom: 'EVALUATE',
    stem: 'A pharmaceutical company identifies compound X that reduces enzyme activity in vitro by 90% at 1 μM. A student concludes it will be an effective drug in vivo. Evaluate this conclusion.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.65, irtB: 1.4, irtC: 0.15,
    options: [
      { label: 'A', text: 'The conclusion is valid because 90% inhibition at 1 μM is excellent potency', justification: 'In vitro potency is necessary but not sufficient; bioavailability, selectivity, toxicity, and pharmacokinetics also matter.', isCorrect: false },
      { label: 'B', text: 'The conclusion is premature; in vitro potency does not guarantee in vivo efficacy due to issues of cell permeability, bioavailability, selectivity, and off-target effects', justification: 'Many potent in vitro inhibitors fail in vivo; the full drug development pipeline must evaluate these additional factors.', isCorrect: true },
      { label: 'C', text: 'The conclusion is incorrect because 90% inhibition is insufficient; 99% would be needed', justification: 'The required inhibition level depends on the pathway and context; the flaw in the conclusion is not about the percent inhibition threshold.', isCorrect: false },
      { label: 'D', text: 'The conclusion is valid because in vitro and in vivo conditions are essentially identical', justification: 'In vitro and in vivo environments differ drastically in protein binding, pH, metabolism, and compartmentalization.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-022',
    bloom: 'EVALUATE',
    stem: 'Is the Lineweaver-Burk plot the best method to determine Km and Vmax? Evaluate its advantages and disadvantages.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.70, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'It is the best method because it gives perfectly linear data and accurate intercepts', justification: 'The double-reciprocal transformation distorts errors and overweights low [S] data points, making it less statistically reliable.', isCorrect: false },
      { label: 'B', text: 'It is useful for visualizing inhibition types but can introduce statistical artifacts due to error distortion from the double-reciprocal transformation; nonlinear regression on direct v vs. [S] data is statistically superior', justification: 'Lineweaver-Burk is pedagogically valuable for visualizing inhibition patterns, but nonlinear regression of raw v vs. [S] data gives more accurate Km and Vmax estimates.', isCorrect: true },
      { label: 'C', text: 'It is no longer used because it was based on incorrect kinetic theory', justification: 'The underlying theory is correct; the limitation is statistical, not theoretical.', isCorrect: false },
      { label: 'D', text: 'It is uniquely superior because all data points carry equal statistical weight', justification: 'The double-reciprocal transformation unequally weights data points, amplifying errors at low [S].', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-023',
    bloom: 'EVALUATE',
    stem: 'Hexokinase has a low Km (~0.1 mM) for glucose, while glucokinase (hexokinase IV) has a high Km (~10 mM) for glucose. Evaluate which enzyme is better suited for the liver\'s glucose-sensing function.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 16',
    irtA: 1.75, irtB: 1.6, irtC: 0.15,
    options: [
      { label: 'A', text: 'Hexokinase (low Km) is better for glucose sensing because it responds to low glucose levels', justification: 'Hexokinase is always saturated at normal blood glucose, making it a poor sensor of elevated glucose.', isCorrect: false },
      { label: 'B', text: 'Glucokinase (high Km) is better for glucose sensing in the liver because its activity is proportional to blood glucose over the postprandial range, signaling when glucose is abundant', justification: 'Glucokinase\'s high Km (~10 mM) means it is not saturated at normal fasting glucose (~5 mM) but increases activity proportionally as blood glucose rises after a meal, making it an ideal glucose sensor.', isCorrect: true },
      { label: 'C', text: 'Both are equally suited for glucose sensing because all hexokinases have similar kinetics in vivo', justification: 'Their very different Km values confer different physiological roles; they are not equivalent.', isCorrect: false },
      { label: 'D', text: 'Neither enzyme performs glucose sensing; that is exclusively performed by insulin receptors', justification: 'Glucokinase is indeed a glucose sensor (part of the "glucostat" mechanism) in pancreatic beta cells and hepatocytes.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-024',
    bloom: 'EVALUATE',
    stem: 'A researcher argues that enzymes near the diffusion limit (kcat/Km ~10⁸–10⁹ M⁻¹s⁻¹) cannot be improved further by evolution. Assess this argument.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.80, irtB: 1.7, irtC: 0.15,
    options: [
      { label: 'A', text: 'The argument is incorrect; enzymes can always be improved by increasing substrate concentration', justification: 'Substrate concentration is not a property of the enzyme itself; the diffusion limit constrains the catalytic efficiency parameter kcat/Km.', isCorrect: false },
      { label: 'B', text: 'The argument is essentially correct; at the diffusion limit, catalysis is limited by substrate encounter rate, not chemistry, so chemical improvement of the active site has no further benefit', justification: 'When kcat/Km approaches the diffusion-controlled limit (~10⁹ M⁻¹s⁻¹), every productive encounter leads to catalysis; further improvements to active site chemistry cannot increase the rate because the bottleneck is now diffusion.', isCorrect: true },
      { label: 'C', text: 'The argument is wrong because diffusion can always be overcome by conformational changes', justification: 'Conformational changes within the enzyme-substrate encounter are already included in the diffusion limit framework; they cannot transcend the physical diffusion ceiling.', isCorrect: false },
      { label: 'D', text: 'The argument is correct, but only applies to intracellular enzymes', justification: 'The diffusion limit applies equally to extracellular and intracellular enzymes.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-025',
    bloom: 'EVALUATE',
    stem: 'Methotrexate competitively inhibits dihydrofolate reductase (DHFR) with extremely high affinity (Ki ~1 pM). Why can it still be used therapeutically without killing normal cells immediately?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.70, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Normal cells lack DHFR entirely', justification: 'All cells have DHFR; normal cells are affected, but cancer cells are more sensitive due to higher proliferative demands.', isCorrect: false },
      { label: 'B', text: 'Cancer cells divide more rapidly and thus require more folate for DNA synthesis, making them more sensitive; dosing exploits this differential sensitivity and the drug is given intermittently to allow normal cell recovery', justification: 'Rapidly dividing cells depend more on DHFR activity for thymidylate synthesis; therapeutic windows exploit this difference and leucovorin rescue protects normal cells.', isCorrect: true },
      { label: 'C', text: 'Methotrexate is exclusively transported into cancer cells and not normal cells', justification: 'While expression of folate transporters differs, methotrexate does enter normal cells; selectivity is not absolute transport exclusion.', isCorrect: false },
      { label: 'D', text: 'Normal cells quickly synthesize new DHFR to replace the inhibited enzyme', justification: 'Rapid protein synthesis is not the primary mechanism of protection; leucovorin rescue and dosing schedules are used clinically.', isCorrect: false },
    ],
  },
  // CREATE (5)
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-026',
    bloom: 'CREATE',
    stem: 'You want to design an experiment to determine whether a newly discovered compound is a competitive or noncompetitive inhibitor. What would your experimental design include?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.80, irtB: 1.6, irtC: 0.15,
    options: [
      { label: 'A', text: 'Measure enzyme activity at a single substrate concentration with and without the inhibitor', justification: 'A single [S] is insufficient to determine inhibitor type; a range of [S] values is needed to assess effects on Km and Vmax.', isCorrect: false },
      { label: 'B', text: 'Measure initial velocities at multiple substrate concentrations in the presence and absence of the inhibitor, then construct Lineweaver-Burk plots to compare Km and Vmax values', justification: 'This is the standard approach: a set of v vs. [S] curves ± inhibitor, plotted as Lineweaver-Burk double reciprocals, reveals whether Km and/or Vmax change, identifying inhibitor type.', isCorrect: true },
      { label: 'C', text: 'Perform a single time course experiment at maximum substrate concentration to determine the final product amount', justification: 'End-point measurements at a single [S] do not reveal inhibitor kinetics.', isCorrect: false },
      { label: 'D', text: 'Test the compound\'s structure to see if it resembles the substrate', justification: 'Structural similarity can suggest competitive inhibition but does not confirm it; kinetic experiments are required.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-027',
    bloom: 'CREATE',
    stem: 'You are designing a new antibiotic targeting bacterial dihydropteroate synthase (DHPS), an enzyme absent in humans. What strategy would maximize selectivity and minimize toxicity?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.85, irtB: 1.7, irtC: 0.15,
    options: [
      { label: 'A', text: 'Design the compound to mimic the transition state of the bacterial DHPS reaction, exploiting structural differences between bacterial and human enzymes', justification: 'Transition-state analogs achieve extremely high affinity and selectivity by complementing the unique active site geometry of the target enzyme.', isCorrect: true },
      { label: 'B', text: 'Design a general protease inhibitor that kills bacteria by degrading all their proteins', justification: 'A general protease inhibitor would be indiscriminate and highly toxic to the host.', isCorrect: false },
      { label: 'C', text: 'Target the bacterial ribosome with a compound that also inhibits human ribosomes at slightly higher doses', justification: 'Targeting shared machinery with narrow selectivity windows risks host toxicity.', isCorrect: false },
      { label: 'D', text: 'Use an extremely high dose of any enzyme inhibitor to overwhelm bacterial defenses', justification: 'High doses of non-selective inhibitors cause toxicity to the host; selectivity is essential.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-028',
    bloom: 'CREATE',
    stem: 'Propose a method to measure the kcat of an enzyme in vitro.',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.75, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Measure Vmax at saturating [S] using a continuous assay, then determine [E]total by active-site titration; kcat = Vmax/[E]total', justification: 'kcat = Vmax/[E]total, where [E]total must be determined by active-site titration (e.g., burst kinetics or stoichiometric inhibitor) to ensure you know the concentration of active enzyme sites.', isCorrect: true },
      { label: 'B', text: 'Measure the initial velocity at [S] = Km; this directly gives kcat', justification: 'At [S] = Km, v = Vmax/2 = kcat[E]total/2; this gives half of kcat×[E]total, not kcat alone.', isCorrect: false },
      { label: 'C', text: 'Measure the time for 50% substrate depletion; this equals 1/kcat', justification: 'The half-life in a first-order reaction equals ln2/kcat, not simply 1/kcat, and this applies only under first-order conditions.', isCorrect: false },
      { label: 'D', text: 'Determine the Km and use the relation kcat = Km × diffusion rate constant', justification: 'There is no such relation; kcat and Km are independent parameters.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-029',
    bloom: 'CREATE',
    stem: 'You want to engineer an enzyme with tighter substrate binding (lower Km) without reducing kcat. Which approach would you propose?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.90, irtB: 1.8, irtC: 0.15,
    options: [
      { label: 'A', text: 'Introduce mutations in the active site that add new H-bond donors/acceptors complementary to the substrate, while leaving catalytic residues intact', justification: 'Adding H-bond interactions to substrate binding improves affinity (lowers Km) without necessarily perturbing the catalytic mechanism (kcat).', isCorrect: true },
      { label: 'B', text: 'Remove all charged residues from the active site to reduce electrostatic repulsion', justification: 'Removing charged residues may disrupt catalysis (kcat) and might not specifically increase substrate affinity.', isCorrect: false },
      { label: 'C', text: 'Increase the overall size of the enzyme by adding residues far from the active site', justification: 'Distant structural changes do not directly improve active-site substrate binding.', isCorrect: false },
      { label: 'D', text: 'Replace the cofactor with a different one to increase substrate binding', justification: 'Cofactor changes would likely alter catalytic mechanism; selective improvement of Km requires targeted active-site engineering.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Enzyme Kinetics',
    externalQuestionId: 'BCH210-EK-030',
    bloom: 'CREATE',
    stem: 'Design a biosensor based on enzyme kinetics to detect a toxic heavy metal that competitively inhibits acetylcholinesterase (AChE).',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 8',
    irtA: 1.95, irtB: 1.9, irtC: 0.15,
    options: [
      { label: 'A', text: 'Immobilize AChE on an electrode; measure the rate of acetylcholine hydrolysis colorimetrically; decreased rate proportional to inhibitor concentration indicates metal presence', justification: 'This is a validated biosensor design: AChE activity is inversely proportional to inhibitor concentration; the colorimetric or electrochemical signal quantifies metal concentration.', isCorrect: true },
      { label: 'B', text: 'Measure the heavy metal directly by atomic absorption spectroscopy without using AChE', justification: 'This detects the metal but does not constitute an enzyme kinetics-based biosensor as specified.', isCorrect: false },
      { label: 'C', text: 'Use gel electrophoresis to separate the heavy metal from AChE', justification: 'Gel electrophoresis separates proteins but is not used in real-time biosensing of inhibitors.', isCorrect: false },
      { label: 'D', text: 'Add excess substrate to the sample; the metal will not inhibit the enzyme due to competition', justification: 'Adding excess substrate would outcompete the inhibitor, eliminating the inhibitory signal and making detection impossible.', isCorrect: false },
    ],
  },

  // ─── Module 3: Carbohydrates & Lipids ────────────────────────────────────────
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-001',
    bloom: 'REMEMBER',
    stem: 'Glucose is classified as which type of monosaccharide?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 11',
    irtA: 0.72, irtB: -1.3, irtC: 0.23,
    options: [
      { label: 'A', text: 'Ketohexose', justification: 'A ketohexose has a ketone group; glucose has an aldehyde group.', isCorrect: false },
      { label: 'B', text: 'Aldohexose', justification: 'Glucose is a six-carbon sugar (hexose) with an aldehyde at C1, making it an aldohexose.', isCorrect: true },
      { label: 'C', text: 'Aldopentose', justification: 'Aldopentoses have five carbons; glucose has six.', isCorrect: false },
      { label: 'D', text: 'Ketopentose', justification: 'Ketopentoses are five-carbon ketone sugars; glucose is neither.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-002',
    bloom: 'REMEMBER',
    stem: 'What type of glycosidic bond links glucose monomers in cellulose?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 11',
    irtA: 0.78, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: 'α(1→4) glycosidic bond', justification: 'α(1→4) bonds are found in starch (amylose), not cellulose.', isCorrect: false },
      { label: 'B', text: 'β(1→4) glycosidic bond', justification: 'Cellulose is composed of glucose units linked by β(1→4) glycosidic bonds, creating straight chains that pack into fibers.', isCorrect: true },
      { label: 'C', text: 'α(1→6) glycosidic bond', justification: 'α(1→6) bonds create branch points in glycogen and amylopectin.', isCorrect: false },
      { label: 'D', text: 'β(1→2) glycosidic bond', justification: 'β(1→2) bonds are found in sucrose (between glucose C1 and fructose C2), not cellulose.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-003',
    bloom: 'UNDERSTAND',
    stem: 'Why are saturated fatty acids solid at room temperature while unsaturated fatty acids are liquid?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 12',
    irtA: 1.05, irtB: -0.2, irtC: 0.20,
    options: [
      { label: 'A', text: 'Saturated fatty acids have more carbon atoms', justification: 'The number of carbons alone does not determine melting point; the degree of saturation is the key factor.', isCorrect: false },
      { label: 'B', text: 'Cis double bonds in unsaturated fatty acids introduce kinks that prevent tight packing, lowering the melting point', justification: 'Cis double bonds create bends in the hydrocarbon chain, preventing close parallel packing and reducing van der Waals interactions, resulting in lower melting points.', isCorrect: true },
      { label: 'C', text: 'Saturated fatty acids carry a positive charge that promotes aggregation', justification: 'Fatty acids are uncharged in their protonated form; charge is not the reason for their physical state.', isCorrect: false },
      { label: 'D', text: 'Unsaturated fatty acids are shorter and therefore more mobile', justification: 'Length and saturation are independent properties; chain length also affects melting point but this is not the key difference described.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-004',
    bloom: 'APPLY',
    stem: 'A phospholipid molecule placed in an aqueous environment will spontaneously form a bilayer. What thermodynamic principle drives this self-assembly?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 12',
    irtA: 1.25, irtB: 0.5, irtC: 0.19,
    options: [
      { label: 'A', text: 'Minimization of enthalpy by forming covalent bonds between lipid tails', justification: 'Lipid bilayer formation does not involve new covalent bonds; it is driven by non-covalent interactions.', isCorrect: false },
      { label: 'B', text: 'The hydrophobic effect: sequestering nonpolar tails away from water maximizes water entropy', justification: 'The hydrophobic effect drives bilayer formation by maximizing the entropy of water molecules, which are freed from ordered clathrate structures around exposed hydrophobic chains.', isCorrect: true },
      { label: 'C', text: 'Electrostatic attraction between phosphate head groups', justification: 'Phosphate groups are negatively charged and would repel each other; they are not the driving force for bilayer formation.', isCorrect: false },
      { label: 'D', text: 'Covalent cross-linking between adjacent phospholipid molecules', justification: 'Phospholipids in a bilayer are held together non-covalently; there is no covalent cross-linking in a standard bilayer.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-005',
    bloom: 'ANALYZE',
    stem: 'Glycogen and starch both use α(1→4) linkages but differ in branching. What functional advantage does glycogen\'s higher branching frequency provide?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 21',
    irtA: 1.45, irtB: 0.9, irtC: 0.17,
    options: [
      { label: 'A', text: 'More branching reduces the solubility of glycogen in the cytoplasm', justification: 'High branching actually increases the surface area for enzymatic attack; solubility is largely maintained.', isCorrect: false },
      { label: 'B', text: 'More branch points provide more free non-reducing ends for simultaneous phosphorylase action, enabling rapid glucose release', justification: 'Glycogen phosphorylase acts at non-reducing ends; the high branching of glycogen (~every 8–12 residues) creates many free ends for rapid, simultaneous mobilization during high energy demand.', isCorrect: true },
      { label: 'C', text: 'More branching increases the caloric density of glycogen compared to starch', justification: 'Branching does not significantly affect caloric density; both store the same amount of energy per glucose unit.', isCorrect: false },
      { label: 'D', text: 'More branching allows glycogen to bind more water, facilitating transport in the blood', justification: 'Glycogen is stored intracellularly, not transported in the blood; the advantage is rapid mobilization.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-006',
    bloom: 'EVALUATE',
    stem: 'A diet high in trans fats is associated with increased cardiovascular disease risk. What structural feature of trans fats explains this association?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 12',
    irtA: 1.60, irtB: 1.2, irtC: 0.16,
    options: [
      { label: 'A', text: 'Trans fats have no double bonds, making them identical to saturated fats in all respects', justification: 'Trans fats do contain double bonds; their geometry (trans rather than cis) is the distinguishing feature.', isCorrect: false },
      { label: 'B', text: 'Trans double bonds allow straight chain packing similar to saturated fats, raising LDL levels and promoting atherogenesis', justification: 'Trans fatty acid chains are relatively straight (unlike kinked cis fats), behave like saturated fats in raising LDL cholesterol, and promote inflammation and plaque formation.', isCorrect: true },
      { label: 'C', text: 'Trans fats are rapidly oxidized, generating harmful free radicals', justification: 'While oxidation of fats can generate radicals, this is not the primary mechanism linking trans fats to cardiovascular disease.', isCorrect: false },
      { label: 'D', text: 'Trans fats contain more calories per gram than other lipids', justification: 'Trans fats have the same caloric density (~9 kcal/g) as other fats; caloric density is not the cardiovascular risk mechanism.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-007',
    bloom: 'ANALYZE',
    stem: 'Cholesterol is found in animal cell membranes but not in plant cell membranes. What functional role does cholesterol play in modulating membrane properties?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 12',
    irtA: 1.40, irtB: 1.0, irtC: 0.18,
    options: [
      { label: 'A', text: 'Cholesterol provides the primary energy reserve for membrane maintenance', justification: 'Cholesterol is a structural component, not an energy reserve; triglycerides serve that role.', isCorrect: false },
      { label: 'B', text: 'Cholesterol acts as a fluidity buffer: at high temperatures it orders the membrane (reduces fluidity) and at low temperatures it disorders it (prevents gel phase)', justification: 'Cholesterol inserts between phospholipids, restricting chain motion at high temperatures and preventing crystallization at low temperatures, maintaining optimal membrane fluidity.', isCorrect: true },
      { label: 'C', text: 'Cholesterol forms covalent bonds with phospholipids to seal the bilayer', justification: 'Cholesterol interacts non-covalently with phospholipids; it does not form covalent bonds.', isCorrect: false },
      { label: 'D', text: 'Cholesterol creates pores that allow selective ion transport', justification: 'Ion transport is performed by dedicated channel proteins, not cholesterol.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::Carbohydrates & Lipids',
    externalQuestionId: 'BCH210-CL-008',
    bloom: 'CREATE',
    stem: 'You are designing a liposome drug delivery system. Which lipid composition change would increase membrane rigidity and reduce drug leakage at body temperature?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 12',
    irtA: 1.75, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Increase the proportion of saturated long-chain phospholipids and add cholesterol', justification: 'Long-chain saturated phospholipids pack tightly, raising the gel-to-liquid transition temperature; cholesterol further orders the bilayer and reduces permeability, collectively reducing drug leakage.', isCorrect: true },
      { label: 'B', text: 'Use only short-chain polyunsaturated phospholipids without cholesterol', justification: 'Short-chain polyunsaturated lipids create a very fluid, leaky membrane — the opposite of what is needed.', isCorrect: false },
      { label: 'C', text: 'Replace all phospholipids with lysophospholipids (single acyl chain)', justification: 'Lysophospholipids form micelles, not bilayers; they would destabilize the liposome structure.', isCorrect: false },
      { label: 'D', text: 'Add negatively charged lipids to increase electrostatic repulsion between bilayer leaflets', justification: 'Increasing electrostatic repulsion would destabilize the bilayer and increase permeability.', isCorrect: false },
    ],
  },

  // ─── Module 4: DNA Replication & Transcription ────────────────────────────────
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-001',
    bloom: 'REMEMBER',
    stem: 'According to the Watson-Crick model, which bases form hydrogen bonds with each other in double-stranded DNA?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 4',
    irtA: 0.70, irtB: -1.4, irtC: 0.24,
    options: [
      { label: 'A', text: 'Adenine with cytosine, guanine with thymine', justification: 'These are not the Watson-Crick base pairs; this pairing would destabilize the double helix.', isCorrect: false },
      { label: 'B', text: 'Adenine with thymine, guanine with cytosine', justification: 'Watson-Crick base pairing: A pairs with T via 2 H-bonds, and G pairs with C via 3 H-bonds.', isCorrect: true },
      { label: 'C', text: 'Adenine with guanine, thymine with cytosine', justification: 'These pairings (purine-purine and pyrimidine-pyrimidine) would produce irregular helix geometry.', isCorrect: false },
      { label: 'D', text: 'Adenine with uracil, guanine with cytosine', justification: 'A-U pairing occurs in RNA; in DNA, adenine pairs with thymine.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-002',
    bloom: 'REMEMBER',
    stem: 'What is the directionality of DNA synthesis by DNA polymerase?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 28',
    irtA: 0.75, irtB: -1.1, irtC: 0.22,
    options: [
      { label: 'A', text: "3' to 5'", justification: "DNA polymerase reads the template 3'→5' but synthesizes the new strand 5'→3'.", isCorrect: false },
      { label: 'B', text: "5' to 3'", justification: "DNA polymerase adds nucleotides to the 3'-OH of the growing strand, synthesizing DNA exclusively in the 5'→3' direction.", isCorrect: true },
      { label: 'C', text: 'Bidirectional simultaneously', justification: "Each DNA polymerase molecule synthesizes in only one direction (5'→3'); bidirectional replication refers to two forks moving in opposite directions, each synthesizing 5'→3'.", isCorrect: false },
      { label: 'D', text: "Both 5'→3' and 3'→5' on different strands", justification: "Both strands are synthesized 5'→3'; the lagging strand achieves this via discontinuous Okazaki fragment synthesis.", isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-003',
    bloom: 'UNDERSTAND',
    stem: "Why is the lagging strand synthesized discontinuously during DNA replication?",
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 28',
    irtA: 1.05, irtB: -0.1, irtC: 0.20,
    options: [
      { label: 'A', text: 'DNA polymerase runs out of nucleotides periodically', justification: 'Nucleotide availability is not the reason; the constraint is the directionality of DNA polymerase.', isCorrect: false },
      { label: 'B', text: "Because DNA polymerase can only synthesize 5'→3', the strand running 3'→5' relative to fork movement must be made in short Okazaki fragments primed repeatedly", justification: "The lagging strand template runs 5'→3' away from the fork. Since DNA polymerase can only work 5'→3', it must repeatedly re-prime in the opposite direction, creating Okazaki fragments.", isCorrect: true },
      { label: 'C', text: 'Helicase can only unwind DNA on the leading strand side', justification: 'Helicase unwinds both strands simultaneously at the replication fork; the discontinuity is due to polymerase directionality.', isCorrect: false },
      { label: 'D', text: "The lagging strand has more mismatches and requires extra proofreading pauses", justification: 'Mismatches trigger proofreading but are not the cause of discontinuous synthesis.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-004',
    bloom: 'APPLY',
    stem: 'A cell treated with a drug that inhibits primase will most directly impair which step of DNA replication?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 28',
    irtA: 1.20, irtB: 0.4, irtC: 0.19,
    options: [
      { label: 'A', text: 'Unwinding of the double helix by helicase', justification: 'Primase inhibition would not directly affect helicase activity.', isCorrect: false },
      { label: 'B', text: 'Synthesis of RNA primers needed by DNA polymerase to begin strand synthesis', justification: 'DNA polymerase III cannot initiate synthesis de novo; it requires a free 3′-OH provided by an RNA primer made by primase. Without primers, replication cannot start.', isCorrect: true },
      { label: 'C', text: 'Proofreading of newly synthesized DNA', justification: 'Proofreading is carried out by the 3′→5′ exonuclease activity of DNA polymerase, not primase.', isCorrect: false },
      { label: 'D', text: 'Ligation of Okazaki fragments', justification: 'Okazaki fragment ligation is performed by DNA ligase, not primase.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-005',
    bloom: 'ANALYZE',
    stem: 'mRNA processing in eukaryotes involves a 5\' cap, intron splicing, and a 3\' poly-A tail. Which of these modifications is primarily important for ribosome recognition?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 29',
    irtA: 1.40, irtB: 0.8, irtC: 0.17,
    options: [
      { label: 'A', text: "The 3' poly-A tail, because ribosomes bind the poly-A sequence directly", justification: "The poly-A tail aids mRNA stability and export; ribosome recruitment is mediated by the 5' cap.", isCorrect: false },
      { label: 'B', text: "The 5' 7-methylguanosine cap, because it is recognized by initiation factor eIF4E to recruit the ribosome", justification: "The m7G cap is recognized by eIF4E, which bridges to the 43S pre-initiation complex, recruiting the small ribosomal subunit to begin translation initiation.", isCorrect: true },
      { label: 'C', text: 'Intron splicing, because ribosomes stall on introns if they are not removed', justification: 'Ribosomes do not distinguish introns directly; splicing removes introns before export from the nucleus.', isCorrect: false },
      { label: 'D', text: "The poly-A tail and 5' cap play equally important roles in ribosome binding", justification: "While both contribute to mRNA stability and translation efficiency, the 5' cap is the primary ribosome recruitment signal.", isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-006',
    bloom: 'EVALUATE',
    stem: 'A mutation in the TATA box of a gene\'s promoter region would most likely have what effect on transcription?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 29',
    irtA: 1.55, irtB: 1.1, irtC: 0.16,
    options: [
      { label: 'A', text: 'No effect, because TATA box mutations are always silent', justification: 'TATA box mutations frequently reduce or abolish transcription initiation.', isCorrect: false },
      { label: 'B', text: 'Reduced or abolished transcription initiation because TATA-binding protein (TBP) cannot recognize the mutated sequence', justification: 'TBP binds the TATA box to nucleate the pre-initiation complex; mutations that disrupt this recognition prevent RNA polymerase II recruitment and reduce transcription.', isCorrect: true },
      { label: 'C', text: 'Enhanced transcription because the mutation relieves transcriptional repression', justification: 'TATA box mutations rarely enhance transcription; they typically reduce TBP binding and initiation.', isCorrect: false },
      { label: 'D', text: 'Altered mRNA splicing patterns because TATA box controls splice site selection', justification: 'The TATA box controls transcription initiation, not RNA splicing; these are mechanistically separate processes.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-007',
    bloom: 'CREATE',
    stem: 'You want to express a human protein in bacteria. Which molecular biology challenge must you address regarding eukaryotic gene structure?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 29',
    irtA: 1.75, irtB: 1.5, irtC: 0.15,
    options: [
      { label: 'A', text: 'Bacteria cannot use human codons', justification: 'The genetic code is nearly universal; codon usage bias may be an issue but bacteria can read human codons in principle.', isCorrect: false },
      { label: 'B', text: 'Bacteria lack the spliceosome machinery to remove introns from eukaryotic pre-mRNA, so you must use cDNA (intron-free) for bacterial expression', justification: 'Eukaryotic genomic DNA contains introns that bacteria cannot splice out; using cDNA (reverse-transcribed from mature mRNA) provides the coding sequence without introns.', isCorrect: true },
      { label: 'C', text: 'Bacteria will add a poly-A tail that destabilizes the mRNA', justification: 'Bacteria do not add poly-A tails to mRNA; this is a eukaryotic process.', isCorrect: false },
      { label: 'D', text: 'Bacteria cannot add a 7-methylguanosine cap, so translation will be impossible', justification: 'Bacterial ribosomes use a Shine-Dalgarno sequence for translation initiation, not a 5\' cap; the cap is not needed in bacteria.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'BCH210_Fall 2024::DNA Replication & Transcription',
    externalQuestionId: 'BCH210-DR-008',
    bloom: 'ANALYZE',
    stem: 'Meselson and Stahl\'s experiment using heavy (¹⁵N) and light (¹⁴N) nitrogen demonstrated which model of DNA replication?',
    reference: 'Stryer Biochemistry, 9th Ed., Ch. 28',
    irtA: 1.35, irtB: 0.7, irtC: 0.18,
    options: [
      { label: 'A', text: 'Conservative replication — the original double helix is conserved intact', justification: 'Conservative replication would produce only fully heavy and fully light duplexes after the second generation; this was not observed.', isCorrect: false },
      { label: 'B', text: 'Semiconservative replication — each daughter duplex retains one original strand', justification: 'After one generation in ¹⁴N medium, all DNA was hybrid (½-heavy); after two generations, equal amounts of hybrid and light DNA appeared — consistent only with semiconservative replication.', isCorrect: true },
      { label: 'C', text: 'Dispersive replication — parental DNA is fragmented and randomly distributed', justification: 'Dispersive replication would produce intermediate-density DNA in all molecules after both generations; the sharp hybrid band after generation 1 ruled this out.', isCorrect: false },
      { label: 'D', text: 'Rolling circle replication — one strand serves as a continuous template', justification: 'Rolling circle replication is used by some phages and plasmids; the Meselson-Stahl experiment addressed chromosomal DNA replication and did not support this model.', isCorrect: false },
    ],
  },
]
