import type { ItemDef } from '../types'

export const CSC108_ITEMS: ItemDef[] = [
  // ─── Module 1: Python Basics & Variables ─────────────────────────────────────
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-001',
    bloom: 'REMEMBER',
    stem: 'What is the output of `type(3.14)` in Python 3?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 0.72, irtB: -1.3, irtC: 0.23,
    options: [
      { label: 'A', text: "<class 'int'>", justification: '3.14 is a float literal, not an integer.', isCorrect: false },
      { label: 'B', text: "<class 'float'>", justification: 'In Python 3, 3.14 is a floating-point number and type() returns <class \'float\'>.', isCorrect: true },
      { label: 'C', text: "<class 'str'>", justification: '3.14 is not enclosed in quotes, so it is not a string.', isCorrect: false },
      { label: 'D', text: 'float', justification: 'type() returns a type object (e.g., <class \'float\'>), not just the bare name.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-002',
    bloom: 'REMEMBER',
    stem: 'Which operator performs integer (floor) division in Python 3?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 0.75, irtB: -1.1, irtC: 0.22,
    options: [
      { label: 'A', text: '/', justification: '/ performs true (float) division in Python 3; 7/2 gives 3.5.', isCorrect: false },
      { label: 'B', text: '//', justification: '// is the floor division operator; 7//2 gives 3 (truncates towards negative infinity).', isCorrect: true },
      { label: 'C', text: '%', justification: '% is the modulo operator, returning the remainder.', isCorrect: false },
      { label: 'D', text: '**', justification: '** is the exponentiation operator.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-003',
    bloom: 'UNDERSTAND',
    stem: 'What does the following code print?\n```python\nx = 5\ny = x\nx = 10\nprint(y)\n```',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 0.90, irtB: -0.5, irtC: 0.21,
    options: [
      { label: 'A', text: '10', justification: 'y was assigned the value of x (5) before x was reassigned to 10; integers are immutable.', isCorrect: false },
      { label: 'B', text: '5', justification: 'y = x copies the value 5 into y. Reassigning x to 10 does not affect y because integers are immutable.', isCorrect: true },
      { label: 'C', text: 'None', justification: 'y has been assigned a value; it would not print None.', isCorrect: false },
      { label: 'D', text: 'Error', justification: 'This code is syntactically valid and runs without error.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-004',
    bloom: 'APPLY',
    stem: 'What is the value of `17 % 5` in Python 3?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 1.05, irtB: 0.1, irtC: 0.20,
    options: [
      { label: 'A', text: '3', justification: '17 = 3×5 + 2, so 17 % 5 = 2, not 3.', isCorrect: false },
      { label: 'B', text: '2', justification: '17 divided by 5 is 3 remainder 2; the modulo operator returns the remainder.', isCorrect: true },
      { label: 'C', text: '3.4', justification: '3.4 is the result of true division 17/5, not modulo.', isCorrect: false },
      { label: 'D', text: '0', justification: '0 would result if 17 were divisible by 5, which it is not.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-005',
    bloom: 'ANALYZE',
    stem: 'A student writes `name = input("Enter name: ")` and then `print("Hello " + name + 5)`. What error will occur?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 1.30, irtB: 0.6, irtC: 0.19,
    options: [
      { label: 'A', text: 'SyntaxError', justification: 'The code is syntactically valid; the error occurs at runtime.', isCorrect: false },
      { label: 'B', text: 'TypeError: can only concatenate str (not "int") to str', justification: 'The + operator cannot concatenate a string and an integer. The integer 5 must be converted to str first.', isCorrect: true },
      { label: 'C', text: 'NameError: name is not defined', justification: 'name is defined by the input() call; there is no NameError.', isCorrect: false },
      { label: 'D', text: 'ValueError', justification: 'ValueError is raised for invalid value conversions, not string-integer concatenation.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-006',
    bloom: 'UNDERSTAND',
    stem: 'What is the result of `int("42")` in Python 3?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 0.80, irtB: -0.8, irtC: 0.22,
    options: [
      { label: 'A', text: '"42" (the string is unchanged)', justification: 'int() converts the value; it does not return the original string.', isCorrect: false },
      { label: 'B', text: '42 (the integer)', justification: 'int("42") converts the string "42" to the integer 42.', isCorrect: true },
      { label: 'C', text: '42.0 (a float)', justification: 'int() produces an integer, not a float; float("42") would give 42.0.', isCorrect: false },
      { label: 'D', text: 'ValueError', justification: '"42" is a valid integer string; int() converts it without error.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Python Basics & Variables',
    externalQuestionId: 'CSC108-PB-007',
    bloom: 'APPLY',
    stem: 'Which f-string correctly formats the variable `score = 95.678` to two decimal places?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 2',
    irtA: 1.15, irtB: 0.3, irtC: 0.20,
    options: [
      { label: 'A', text: 'f"{score:2f}"', justification: ':2f is not the correct format spec; it does not specify decimal places correctly.', isCorrect: false },
      { label: 'B', text: 'f"{score:.2f}"', justification: 'The format spec :.2f means floating-point with 2 decimal places; this would output 95.68.', isCorrect: true },
      { label: 'C', text: 'f"{score, 2}"', justification: 'This is not valid Python f-string formatting syntax.', isCorrect: false },
      { label: 'D', text: 'f"[score:.2f]"', justification: 'Square brackets are not used in f-strings; curly braces {} are required.', isCorrect: false },
    ],
  },

  // ─── Module 2: Control Flow & Functions ──────────────────────────────────────
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-001',
    bloom: 'REMEMBER',
    stem: 'What is the output of `range(0, 10, 3)` converted to a list?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 4',
    irtA: 0.78, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: '[0, 3, 6, 9]', justification: 'range(0, 10, 3) starts at 0, increments by 3, stopping before 10: 0, 3, 6, 9.', isCorrect: true },
      { label: 'B', text: '[0, 3, 6, 9, 12]', justification: 'The stop value is 10 (exclusive); 12 is beyond the stop.', isCorrect: false },
      { label: 'C', text: '[0, 3, 6]', justification: '9 is less than 10 so it is included; the list has 4 elements.', isCorrect: false },
      { label: 'D', text: '[1, 4, 7, 10]', justification: 'range starts at 0, not 1, when the start argument is explicitly 0.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-002',
    bloom: 'UNDERSTAND',
    stem: 'What is the difference between `break` and `continue` inside a loop?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 4',
    irtA: 0.95, irtB: -0.3, irtC: 0.20,
    options: [
      { label: 'A', text: '`break` skips the current iteration; `continue` exits the loop entirely', justification: 'This is reversed; break exits the loop and continue skips the current iteration.', isCorrect: false },
      { label: 'B', text: '`break` exits the loop immediately; `continue` skips the rest of the current iteration and moves to the next', justification: 'break terminates the loop; continue jumps to the next loop iteration, skipping remaining code in the current one.', isCorrect: true },
      { label: 'C', text: 'Both `break` and `continue` exit the loop', justification: 'Only break exits the loop; continue moves to the next iteration.', isCorrect: false },
      { label: 'D', text: '`break` and `continue` are identical in behavior', justification: 'They have distinct behaviors: break exits the loop, continue skips to the next iteration.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-003',
    bloom: 'APPLY',
    stem: 'What does this function return when called as `mystery(4)`?\n```python\ndef mystery(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total\n```',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 3',
    irtA: 1.10, irtB: 0.2, irtC: 0.19,
    options: [
      { label: 'A', text: '4', justification: 'The function sums 1+2+3+4 = 10, not just 4.', isCorrect: false },
      { label: 'B', text: '10', justification: 'range(1, 5) produces 1, 2, 3, 4; total = 0+1+2+3+4 = 10.', isCorrect: true },
      { label: 'C', text: '6', justification: '6 would be the sum up to 3 (1+2+3); the function goes up to n=4.', isCorrect: false },
      { label: 'D', text: '0', justification: 'total starts at 0 but is accumulated through the loop; it does not remain 0.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-004',
    bloom: 'ANALYZE',
    stem: 'A function is defined as `def greet(name, greeting="Hello"):`. Which call is valid?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 3',
    irtA: 1.15, irtB: 0.4, irtC: 0.20,
    options: [
      { label: 'A', text: 'greet()', justification: '`name` has no default and is required; calling greet() without arguments raises a TypeError.', isCorrect: false },
      { label: 'B', text: 'greet("Alice")', justification: '"Alice" provides the required `name` argument; `greeting` uses its default value "Hello".', isCorrect: true },
      { label: 'C', text: 'greet(greeting="Hi")', justification: '`name` is still required; providing only the keyword argument `greeting` raises a TypeError.', isCorrect: false },
      { label: 'D', text: 'greet("Alice", "Bob", "Carol")', justification: 'The function accepts at most 2 arguments; passing 3 raises a TypeError.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-005',
    bloom: 'UNDERSTAND',
    stem: 'What is the scope of a variable defined inside a function in Python?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 3',
    irtA: 0.90, irtB: -0.2, irtC: 0.21,
    options: [
      { label: 'A', text: 'Global — accessible everywhere in the module', justification: 'Variables defined inside a function are local by default, not global.', isCorrect: false },
      { label: 'B', text: 'Local — accessible only within that function', justification: 'In Python, variables assigned inside a function are local to that function and cannot be accessed outside it without the `global` keyword.', isCorrect: true },
      { label: 'C', text: 'Module-level — accessible to all functions in the same file', justification: 'Module-level (global) scope requires variables to be defined outside functions or declared with `global`.', isCorrect: false },
      { label: 'D', text: 'Class-level — accessible to all instances', justification: 'Class scope is separate; function variables are local unless explicitly declared otherwise.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-006',
    bloom: 'APPLY',
    stem: 'What is printed by this code?\n```python\nfor i in range(5):\n    if i == 3:\n        break\n    print(i)\n```',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 4',
    irtA: 1.20, irtB: 0.3, irtC: 0.19,
    options: [
      { label: 'A', text: '0 1 2 3', justification: 'When i == 3, break exits the loop before print(i) executes for i=3.', isCorrect: false },
      { label: 'B', text: '0 1 2', justification: 'The loop prints 0, 1, 2; when i becomes 3 the break exits before printing.', isCorrect: true },
      { label: 'C', text: '0 1 2 3 4', justification: 'The break statement stops the loop at i==3; 3 and 4 are never printed.', isCorrect: false },
      { label: 'D', text: '1 2 3 4', justification: 'range(5) starts at 0; the first printed value is 0.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Control Flow & Functions',
    externalQuestionId: 'CSC108-CF-007',
    bloom: 'ANALYZE',
    stem: 'Which of the following correctly documents a function using a docstring?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 3',
    irtA: 1.05, irtB: 0.0, irtC: 0.20,
    options: [
      { label: 'A', text: 'def add(a, b): # Returns sum', justification: 'A comment (#) is not a docstring; it does not appear in help() output.', isCorrect: false },
      { label: 'B', text: 'def add(a, b):\n    """Return the sum of a and b."""\n    return a + b', justification: 'A triple-quoted string immediately after the function header is a docstring; it is accessible via help(add) and __doc__.', isCorrect: true },
      { label: 'C', text: 'def add(a, b):\n    return a + b\n    """Return the sum."""', justification: 'A string after the return statement is unreachable and is not recognized as a docstring.', isCorrect: false },
      { label: 'D', text: "def add(a, b):\n    'Return sum'\n    return a + b", justification: "A single-quoted string can technically be a docstring but triple quotes (\"\"\" \"\"\") are the Python convention.", isCorrect: false },
    ],
  },

  // ─── Module 3: Lists, Strings & Loops ────────────────────────────────────────
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-001',
    bloom: 'REMEMBER',
    stem: 'What does `len([1, 2, 3, 4])` return in Python 3?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 8',
    irtA: 0.65, irtB: -1.5, irtC: 0.25,
    options: [
      { label: 'A', text: '3', justification: 'The list has 4 elements; len() returns the count of elements.', isCorrect: false },
      { label: 'B', text: '4', justification: 'len([1, 2, 3, 4]) counts the four elements and returns 4.', isCorrect: true },
      { label: 'C', text: '10', justification: '10 is the sum of the elements, not their count.', isCorrect: false },
      { label: 'D', text: '[4]', justification: 'len() returns an integer, not a list.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-002',
    bloom: 'UNDERSTAND',
    stem: 'What is the result of `"Hello, World!".split(",")`?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 9',
    irtA: 0.85, irtB: -0.6, irtC: 0.21,
    options: [
      { label: 'A', text: '["Hello", "World!"]', justification: 'split(",") splits on the comma; the resulting strings are "Hello" and " World!" (note the space before World).', isCorrect: false },
      { label: 'B', text: '["Hello", " World!"]', justification: 'split(",") splits the string at the comma; the second element retains the leading space.', isCorrect: true },
      { label: 'C', text: '["H","e","l","l","o",","," ","W","o","r","l","d","!"]', justification: 'split() without a separator splits on whitespace; split(",") splits only on the comma character.', isCorrect: false },
      { label: 'D', text: '"Hello World!"', justification: 'split() returns a list, not a single string.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-003',
    bloom: 'APPLY',
    stem: 'What is the output of this code?\n```python\nwords = ["cat", "bat", "hat"]\nwords.sort()\nprint(words[0])\n```',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 8',
    irtA: 1.10, irtB: 0.2, irtC: 0.20,
    options: [
      { label: 'A', text: 'cat', justification: 'sort() sorts alphabetically; "bat" comes before "cat" and "hat".', isCorrect: false },
      { label: 'B', text: 'bat', justification: 'Alphabetical sort: ["bat", "cat", "hat"]; words[0] is "bat".', isCorrect: true },
      { label: 'C', text: 'hat', justification: '"hat" is the last element alphabetically; words[0] is the first.', isCorrect: false },
      { label: 'D', text: 'None', justification: 'sort() returns None but modifies the list in place; print(words[0]) prints the first element.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-004',
    bloom: 'APPLY',
    stem: 'What does `"python"[1:4]` return?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 9',
    irtA: 1.05, irtB: 0.1, irtC: 0.20,
    options: [
      { label: 'A', text: '"pyt"', justification: '"pyt" would be indices 0:3, not 1:4.', isCorrect: false },
      { label: 'B', text: '"yth"', justification: 'Indices 1, 2, 3 of "python" are \'y\', \'t\', \'h\'; slicing [1:4] returns "yth".', isCorrect: true },
      { label: 'C', text: '"ytho"', justification: '"ytho" would be indices 1:5, not 1:4.', isCorrect: false },
      { label: 'D', text: '"ython"', justification: '"ython" would be [1:] or [1:6], not [1:4].', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-005',
    bloom: 'ANALYZE',
    stem: 'What is the output of `[x**2 for x in range(4) if x % 2 == 0]`?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 8',
    irtA: 1.35, irtB: 0.7, irtC: 0.18,
    options: [
      { label: 'A', text: '[0, 1, 4, 9]', justification: 'This would be [x**2 for x in range(4)] without the filter condition.', isCorrect: false },
      { label: 'B', text: '[0, 4]', justification: 'Even numbers in range(4) are 0 and 2; 0**2=0 and 2**2=4; result is [0, 4].', isCorrect: true },
      { label: 'C', text: '[1, 9]', justification: '[1, 9] would be the squares of odd numbers (1 and 3).', isCorrect: false },
      { label: 'D', text: '[0, 2, 4]', justification: 'This would be the even numbers themselves, not their squares.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-006',
    bloom: 'UNDERSTAND',
    stem: 'What is the difference between `list.append(x)` and `list.extend(x)`?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 8',
    irtA: 0.95, irtB: -0.1, irtC: 0.21,
    options: [
      { label: 'A', text: 'append adds a single element; extend adds each element of an iterable individually', justification: 'append(x) adds x as one element (even if x is a list); extend(x) iterates over x and adds each item individually.', isCorrect: true },
      { label: 'B', text: 'extend adds a single element; append adds each element of an iterable', justification: 'This is the reverse of the correct answer.', isCorrect: false },
      { label: 'C', text: 'Both append and extend add all elements of an iterable', justification: 'Only extend iterates over the argument; append adds the entire argument as one element.', isCorrect: false },
      { label: 'D', text: 'append and extend are identical', justification: 'append([1,2]) adds [1,2] as a nested list; extend([1,2]) adds 1 and 2 as separate elements.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::Lists, Strings & Loops',
    externalQuestionId: 'CSC108-LS-007',
    bloom: 'ANALYZE',
    stem: 'Given `s = "Hello"`, what is `s.lower().replace("h", "j")`?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 9',
    irtA: 1.20, irtB: 0.5, irtC: 0.19,
    options: [
      { label: 'A', text: '"Hello"', justification: 'lower() converts "Hello" to "hello"; replace then substitutes "h" with "j".', isCorrect: false },
      { label: 'B', text: '"jello"', justification: 's.lower() gives "hello"; "hello".replace("h","j") gives "jello".', isCorrect: true },
      { label: 'C', text: '"Hello".replace("H","j") = "jello"', justification: 'lower() is applied first, producing "hello"; replace then targets lowercase "h".', isCorrect: false },
      { label: 'D', text: '"Jello"', justification: 'lower() was called first, so all characters are lowercase before replace; the result is "jello" not "Jello".', isCorrect: false },
    ],
  },

  // ─── Module 4: File I/O & Exceptions ─────────────────────────────────────────
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-001',
    bloom: 'REMEMBER',
    stem: 'Which mode opens a file for writing and creates the file if it does not exist, overwriting any existing content?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 10',
    irtA: 0.75, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: '"r"', justification: '"r" opens a file for reading only; it raises FileNotFoundError if the file does not exist.', isCorrect: false },
      { label: 'B', text: '"w"', justification: '"w" opens for writing, creates the file if absent, and truncates (overwrites) existing content.', isCorrect: true },
      { label: 'C', text: '"a"', justification: '"a" opens for appending; it creates the file if absent but does not overwrite existing content.', isCorrect: false },
      { label: 'D', text: '"x"', justification: '"x" creates a new file but raises FileExistsError if the file already exists.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-002',
    bloom: 'UNDERSTAND',
    stem: 'What is the advantage of using `with open(...) as f:` over `f = open(...)` / `f.close()`?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 10',
    irtA: 0.92, irtB: -0.3, irtC: 0.20,
    options: [
      { label: 'A', text: 'The `with` statement reads the file faster', justification: 'The `with` statement does not improve I/O speed; its benefit is automatic resource management.', isCorrect: false },
      { label: 'B', text: 'The `with` statement automatically closes the file even if an exception occurs, preventing resource leaks', justification: 'A context manager guarantees __exit__ is called, closing the file handle whether or not an exception is raised.', isCorrect: true },
      { label: 'C', text: 'The `with` statement allows reading binary and text files simultaneously', justification: 'Context managers do not enable simultaneous binary/text reading; the mode must still be specified separately.', isCorrect: false },
      { label: 'D', text: 'The `with` statement is required by Python 3 for all file operations', justification: 'Manual open/close is still valid in Python 3; `with` is strongly recommended but not mandatory.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-003',
    bloom: 'APPLY',
    stem: 'What exception is raised when you try to open a file that does not exist in read mode?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 10',
    irtA: 1.05, irtB: 0.0, irtC: 0.20,
    options: [
      { label: 'A', text: 'ValueError', justification: 'ValueError is raised for invalid argument values, not missing files.', isCorrect: false },
      { label: 'B', text: 'FileNotFoundError', justification: 'FileNotFoundError (a subclass of OSError) is raised when a file specified for reading does not exist.', isCorrect: true },
      { label: 'C', text: 'TypeError', justification: 'TypeError is raised for wrong argument types, not missing files.', isCorrect: false },
      { label: 'D', text: 'IOError', justification: 'IOError is an alias for OSError in Python 3; the more specific FileNotFoundError is what Python actually raises.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-004',
    bloom: 'APPLY',
    stem: 'What does this code print if `data.txt` contains one line: `"42\\n"`?\n```python\nwith open("data.txt") as f:\n    line = f.readline()\nprint(int(line))\n```',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 10',
    irtA: 1.20, irtB: 0.4, irtC: 0.19,
    options: [
      { label: 'A', text: '"42\\n"', justification: 'int() strips whitespace including the newline and converts "42\\n" to the integer 42.', isCorrect: false },
      { label: 'B', text: '42', justification: 'readline() reads "42\\n"; int() ignores leading/trailing whitespace and converts the string to integer 42.', isCorrect: true },
      { label: 'C', text: 'ValueError', justification: 'int() handles trailing newlines by stripping whitespace; no ValueError is raised.', isCorrect: false },
      { label: 'D', text: '42.0', justification: 'int() returns an integer, not a float.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-005',
    bloom: 'ANALYZE',
    stem: 'What is the purpose of the `finally` clause in a try/except/finally block?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 11',
    irtA: 1.30, irtB: 0.6, irtC: 0.18,
    options: [
      { label: 'A', text: 'It runs only if no exception was raised', justification: 'The `finally` clause runs whether or not an exception occurred.', isCorrect: false },
      { label: 'B', text: 'It runs only if an exception was raised', justification: 'This describes the `except` clause, not `finally`.', isCorrect: false },
      { label: 'C', text: 'It always runs regardless of whether an exception occurred, used for cleanup code', justification: '`finally` is guaranteed to execute in all cases (exception, no exception, or even after a return/break), making it ideal for cleanup like closing files or releasing resources.', isCorrect: true },
      { label: 'D', text: 'It suppresses all exceptions raised in the try block', justification: '`finally` does not suppress exceptions; only `except` clauses handle/suppress specific exceptions.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-006',
    bloom: 'ANALYZE',
    stem: 'A student writes `int("hello")`. Which exception is raised?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 11',
    irtA: 1.10, irtB: 0.3, irtC: 0.20,
    options: [
      { label: 'A', text: 'TypeError', justification: 'TypeError is raised when an operation is applied to an inappropriate type (e.g., adding str and int), not when a conversion fails.', isCorrect: false },
      { label: 'B', text: 'ValueError', justification: 'int() accepts a string argument (correct type) but raises ValueError when the string cannot be interpreted as an integer.', isCorrect: true },
      { label: 'C', text: 'NameError', justification: 'NameError is raised when a name is undefined; "hello" is a valid string literal.', isCorrect: false },
      { label: 'D', text: 'SyntaxError', justification: 'SyntaxError occurs at parse time; int("hello") is syntactically valid but raises a runtime ValueError.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC108_Winter 2025::File I/O & Exceptions',
    externalQuestionId: 'CSC108-FI-007',
    bloom: 'EVALUATE',
    stem: 'Which approach is better for reading a large file line by line in Python, and why?',
    reference: 'Gries, Campbell & Montojo, Practical Programming, 3rd Ed., Ch. 10',
    irtA: 1.45, irtB: 0.9, irtC: 0.17,
    options: [
      { label: 'A', text: '`f.read()` followed by splitting on newlines — reads everything at once for speed', justification: 'read() loads the entire file into memory; for large files this can cause memory exhaustion.', isCorrect: false },
      { label: 'B', text: 'Iterating directly over the file object `for line in f:` — reads one line at a time, memory-efficient', justification: 'Iterating over a file object uses lazy evaluation, loading one line at a time, making it suitable for arbitrarily large files without loading the whole file into memory.', isCorrect: true },
      { label: 'C', text: '`f.readlines()` — returns a list of all lines at once for easy indexing', justification: 'readlines() loads all lines into a list in memory; for large files this is inefficient.', isCorrect: false },
      { label: 'D', text: 'Both approaches are equivalent in memory usage for all file sizes', justification: 'read() and readlines() load the entire file; iteration is memory-efficient and is not equivalent.', isCorrect: false },
    ],
  },
]
