import type { ItemDef } from '../types'

export const OTHER_COURSE_ITEMS: ItemDef[] = [
  // ─── CSC207: Software Design (Fall 2024) ──────────────────────────────────────
  // Object-Oriented Design
  {
    moduleKey: 'CSC207_Fall 2024::Object-Oriented Design',
    externalQuestionId: 'CSC207-OD-001',
    bloom: 'REMEMBER',
    stem: 'Which OOP principle states that a class should expose only what is necessary and hide implementation details?',
    reference: 'Bloch, Effective Java, 3rd Ed.',
    irtA: 0.80, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: 'Inheritance', justification: 'Inheritance is about extending classes, not hiding details.', isCorrect: false },
      { label: 'B', text: 'Encapsulation', justification: 'Encapsulation bundles data and methods while restricting external access to internals.', isCorrect: true },
      { label: 'C', text: 'Polymorphism', justification: 'Polymorphism allows objects to be treated as instances of a parent type.', isCorrect: false },
      { label: 'D', text: 'Abstraction', justification: 'Abstraction is related but refers more broadly to hiding complexity behind interfaces.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC207_Fall 2024::Object-Oriented Design',
    externalQuestionId: 'CSC207-OD-002',
    bloom: 'UNDERSTAND',
    stem: 'What does the Liskov Substitution Principle (LSP) state?',
    reference: 'Bloch, Effective Java, 3rd Ed.',
    irtA: 1.10, irtB: 0.3, irtC: 0.19,
    options: [
      { label: 'A', text: 'A class should have only one reason to change', justification: 'That is the Single Responsibility Principle.', isCorrect: false },
      { label: 'B', text: 'Subtypes must be substitutable for their base types without altering program correctness', justification: 'LSP requires that objects of a subclass can replace objects of the superclass without breaking the program.', isCorrect: true },
      { label: 'C', text: 'Classes should be open for extension but closed for modification', justification: 'That is the Open/Closed Principle.', isCorrect: false },
      { label: 'D', text: 'Depend on abstractions, not concretions', justification: 'That is the Dependency Inversion Principle.', isCorrect: false },
    ],
  },
  // Design Patterns
  {
    moduleKey: 'CSC207_Fall 2024::Design Patterns',
    externalQuestionId: 'CSC207-DP-001',
    bloom: 'REMEMBER',
    stem: 'The Singleton pattern ensures that a class has how many instances?',
    reference: 'Gamma et al., Design Patterns, Ch. 3',
    irtA: 0.75, irtB: -1.1, irtC: 0.23,
    options: [
      { label: 'A', text: 'Zero', justification: 'Singleton ensures at least one instance exists.', isCorrect: false },
      { label: 'B', text: 'Exactly one', justification: 'The Singleton pattern restricts instantiation to a single object and provides a global access point.', isCorrect: true },
      { label: 'C', text: 'Two', justification: 'Two instances would violate the Singleton constraint.', isCorrect: false },
      { label: 'D', text: 'Unlimited', justification: 'Unlimited instances is the default behavior without the Singleton pattern.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC207_Fall 2024::Design Patterns',
    externalQuestionId: 'CSC207-DP-002',
    bloom: 'UNDERSTAND',
    stem: 'In the Observer pattern, what is the relationship between Subject and Observer?',
    reference: 'Gamma et al., Design Patterns, Ch. 5',
    irtA: 1.05, irtB: 0.1, irtC: 0.20,
    options: [
      { label: 'A', text: 'Observer inherits from Subject', justification: 'Observer and Subject are not in an inheritance relationship; they communicate via a registration/notification interface.', isCorrect: false },
      { label: 'B', text: 'Subject maintains a list of Observers and notifies them of state changes', justification: 'The Subject (publisher) holds references to Observers (subscribers) and calls their update method when its state changes.', isCorrect: true },
      { label: 'C', text: 'Observer creates and destroys Subject instances', justification: 'Observers react to Subject changes; they do not manage Subject lifecycle.', isCorrect: false },
      { label: 'D', text: 'Subject and Observer share the same interface', justification: 'They have separate roles; Subject notifies, Observer reacts.', isCorrect: false },
    ],
  },
  // Testing & Refactoring
  {
    moduleKey: 'CSC207_Fall 2024::Testing & Refactoring',
    externalQuestionId: 'CSC207-TR-001',
    bloom: 'REMEMBER',
    stem: 'In test-driven development (TDD), what is the correct order of steps?',
    reference: 'Beck, Test-Driven Development by Example',
    irtA: 0.82, irtB: -0.9, irtC: 0.21,
    options: [
      { label: 'A', text: 'Write code → Write test → Refactor', justification: 'TDD requires writing the failing test before writing any production code.', isCorrect: false },
      { label: 'B', text: 'Write failing test → Write minimal code to pass → Refactor', justification: 'Red–Green–Refactor: first write a failing test (red), then write minimal code to pass it (green), then clean up (refactor).', isCorrect: true },
      { label: 'C', text: 'Refactor → Write test → Write code', justification: 'Refactoring comes last in TDD, not first.', isCorrect: false },
      { label: 'D', text: 'Write test → Refactor → Write code', justification: 'Refactoring must happen after code passes; writing code comes before refactoring.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC207_Fall 2024::Testing & Refactoring',
    externalQuestionId: 'CSC207-TR-002',
    bloom: 'UNDERSTAND',
    stem: 'What is a "code smell" in software engineering?',
    reference: 'Fowler, Refactoring, 2nd Ed.',
    irtA: 0.95, irtB: -0.2, irtC: 0.20,
    options: [
      { label: 'A', text: 'A runtime error caused by bad memory management', justification: 'Code smells are structural issues in code, not runtime errors.', isCorrect: false },
      { label: 'B', text: 'A surface indicator in source code that may signal a deeper design problem', justification: 'Code smells (e.g., long methods, duplicate code, large classes) are symptoms of potential design flaws that warrant refactoring.', isCorrect: true },
      { label: 'C', text: 'A security vulnerability found by static analysis', justification: 'Security vulnerabilities are a separate concern from code smells, though bad code can enable both.', isCorrect: false },
      { label: 'D', text: 'A performance bottleneck detected by a profiler', justification: 'Performance issues are identified by profiling; code smells are structural/design concerns.', isCorrect: false },
    ],
  },

  // ─── CSC343: Introduction to Databases (Winter 2025) ──────────────────────────
  // Relational Model & SQL
  {
    moduleKey: 'CSC343_Winter 2025::Relational Model & SQL',
    externalQuestionId: 'CSC343-SQL-001',
    bloom: 'REMEMBER',
    stem: 'Which SQL keyword removes duplicate rows from a query result?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 0.78, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: 'UNIQUE', justification: 'UNIQUE is a constraint, not a query keyword for removing duplicates.', isCorrect: false },
      { label: 'B', text: 'DISTINCT', justification: 'SELECT DISTINCT eliminates duplicate rows from the result set.', isCorrect: true },
      { label: 'C', text: 'FILTER', justification: 'FILTER is not standard SQL for removing duplicates.', isCorrect: false },
      { label: 'D', text: 'GROUP BY', justification: 'GROUP BY groups rows but does not by itself remove duplicates from ungrouped queries.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC343_Winter 2025::Relational Model & SQL',
    externalQuestionId: 'CSC343-SQL-002',
    bloom: 'APPLY',
    stem: 'Which SQL clause filters groups after a GROUP BY, rather than filtering individual rows?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 1.10, irtB: 0.2, irtC: 0.19,
    options: [
      { label: 'A', text: 'WHERE', justification: 'WHERE filters individual rows before grouping.', isCorrect: false },
      { label: 'B', text: 'HAVING', justification: 'HAVING applies conditions to groups after GROUP BY, e.g., HAVING COUNT(*) > 5.', isCorrect: true },
      { label: 'C', text: 'ORDER BY', justification: 'ORDER BY sorts the result; it does not filter groups.', isCorrect: false },
      { label: 'D', text: 'LIMIT', justification: 'LIMIT restricts the number of rows returned, not group-level filtering.', isCorrect: false },
    ],
  },
  // Query Optimization
  {
    moduleKey: 'CSC343_Winter 2025::Query Optimization',
    externalQuestionId: 'CSC343-QO-001',
    bloom: 'UNDERSTAND',
    stem: 'What is the primary purpose of a database index?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 0.90, irtB: -0.5, irtC: 0.21,
    options: [
      { label: 'A', text: 'To enforce referential integrity between tables', justification: 'Referential integrity is enforced by foreign key constraints, not indexes.', isCorrect: false },
      { label: 'B', text: 'To speed up data retrieval by providing a fast lookup structure', justification: 'An index (e.g., B-tree) allows the database to locate rows without scanning the entire table.', isCorrect: true },
      { label: 'C', text: 'To compress data to reduce storage size', justification: 'Indexes actually consume additional storage; their purpose is retrieval speed, not compression.', isCorrect: false },
      { label: 'D', text: 'To automatically sort query results', justification: 'Indexes can support ordered scans but do not automatically sort results without an ORDER BY clause.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC343_Winter 2025::Query Optimization',
    externalQuestionId: 'CSC343-QO-002',
    bloom: 'ANALYZE',
    stem: 'A table has 1 million rows. A query filters on an unindexed column. What is the typical access pattern?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 1.20, irtB: 0.5, irtC: 0.19,
    options: [
      { label: 'A', text: 'Index scan — only relevant rows are read', justification: 'Without an index, an index scan is not possible.', isCorrect: false },
      { label: 'B', text: 'Full table scan — every row must be examined', justification: 'Without an index, the database reads every row to find those matching the predicate (O(n) cost).', isCorrect: true },
      { label: 'C', text: 'Hash join — rows are hashed and compared', justification: 'Hash join is used for join operations between two tables, not single-table lookups.', isCorrect: false },
      { label: 'D', text: 'Bitmap scan — a bitmap marks matching rows', justification: 'Bitmap scans require an index; without one, a full scan is performed.', isCorrect: false },
    ],
  },
  // Transactions & Concurrency
  {
    moduleKey: 'CSC343_Winter 2025::Transactions & Concurrency',
    externalQuestionId: 'CSC343-TC-001',
    bloom: 'REMEMBER',
    stem: 'What does the "A" in ACID stand for?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 0.72, irtB: -1.2, irtC: 0.23,
    options: [
      { label: 'A', text: 'Authorization', justification: 'Authorization relates to access control, not ACID properties.', isCorrect: false },
      { label: 'B', text: 'Atomicity', justification: 'Atomicity means a transaction is all-or-nothing: either all operations complete or none do.', isCorrect: true },
      { label: 'C', text: 'Availability', justification: 'Availability is a property in the CAP theorem, not ACID.', isCorrect: false },
      { label: 'D', text: 'Aggregation', justification: 'Aggregation is a SQL concept unrelated to ACID.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC343_Winter 2025::Transactions & Concurrency',
    externalQuestionId: 'CSC343-TC-002',
    bloom: 'UNDERSTAND',
    stem: 'What is a deadlock in a database system?',
    reference: 'Ramakrishnan & Gehrke, Database Management Systems, 3rd Ed.',
    irtA: 1.00, irtB: 0.0, irtC: 0.20,
    options: [
      { label: 'A', text: 'A transaction that runs for too long and is automatically rolled back', justification: 'That describes a timeout or long-running transaction, not a deadlock.', isCorrect: false },
      { label: 'B', text: 'A cycle of transactions each waiting for a lock held by another, causing all to be stuck indefinitely', justification: 'Deadlock: T1 holds lock A and waits for B; T2 holds B and waits for A — neither can proceed.', isCorrect: true },
      { label: 'C', text: 'A transaction that corrupts data due to a write conflict', justification: 'Data corruption from write conflicts is a concurrency anomaly, not necessarily a deadlock.', isCorrect: false },
      { label: 'D', text: 'A database that runs out of storage space', justification: 'Storage exhaustion is an operational issue unrelated to transaction deadlocks.', isCorrect: false },
    ],
  },

  // ─── CSC369: Operating Systems (Fall 2024) ────────────────────────────────────
  {
    moduleKey: 'CSC369_Fall 2024::Processes & Threads',
    externalQuestionId: 'CSC369-PT-001',
    bloom: 'REMEMBER',
    stem: 'What is the difference between a process and a thread?',
    reference: 'Silberschatz, Operating System Concepts, 10th Ed.',
    irtA: 0.85, irtB: -0.8, irtC: 0.21,
    options: [
      { label: 'A', text: 'A thread has its own memory space; a process shares memory with others', justification: 'This is reversed: processes have separate memory; threads share memory within a process.', isCorrect: false },
      { label: 'B', text: 'A process has its own memory space; threads within a process share memory', justification: 'Processes are isolated; threads are lightweight execution units that share the heap and global data of their parent process.', isCorrect: true },
      { label: 'C', text: 'Processes and threads are identical in modern operating systems', justification: 'They differ in isolation, overhead, and memory sharing.', isCorrect: false },
      { label: 'D', text: 'A thread can run on multiple CPUs simultaneously; a process cannot', justification: 'Both processes and threads can be scheduled across CPUs; threads of the same process share memory.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC369_Fall 2024::Processes & Threads',
    externalQuestionId: 'CSC369-PT-002',
    bloom: 'UNDERSTAND',
    stem: 'What is a race condition?',
    reference: 'Silberschatz, Operating System Concepts, 10th Ed.',
    irtA: 1.00, irtB: -0.2, irtC: 0.20,
    options: [
      { label: 'A', text: 'A CPU scheduling algorithm that prioritizes fast processes', justification: 'This describes a scheduling policy, not a race condition.', isCorrect: false },
      { label: 'B', text: 'A situation where the outcome depends on the non-deterministic ordering of concurrent operations accessing shared data', justification: 'A race condition occurs when two or more threads access shared data concurrently and the result depends on the order of execution.', isCorrect: true },
      { label: 'C', text: 'A deadlock between exactly two threads', justification: 'Deadlock is a separate problem; race conditions involve unpredictable outcomes, not necessarily blocking.', isCorrect: false },
      { label: 'D', text: 'An OS scheduler bug that skips a process indefinitely', justification: 'That describes starvation, not a race condition.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC369_Fall 2024::Memory Management',
    externalQuestionId: 'CSC369-MM-001',
    bloom: 'REMEMBER',
    stem: 'What is the purpose of a Translation Lookaside Buffer (TLB)?',
    reference: 'Silberschatz, Operating System Concepts, 10th Ed.',
    irtA: 0.88, irtB: -0.7, irtC: 0.21,
    options: [
      { label: 'A', text: 'To store recently used disk blocks in RAM', justification: 'That describes a disk buffer cache, not a TLB.', isCorrect: false },
      { label: 'B', text: 'To cache recent virtual-to-physical address translations for fast memory access', justification: 'The TLB is a hardware cache that stores page table entries, avoiding a full page table walk on every memory access.', isCorrect: true },
      { label: 'C', text: 'To manage the swap space on disk', justification: 'Swap management is handled by the OS, not the TLB.', isCorrect: false },
      { label: 'D', text: 'To enforce memory protection between processes', justification: 'Memory protection uses page table permission bits; the TLB speeds up address translation.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC369_Fall 2024::Memory Management',
    externalQuestionId: 'CSC369-MM-002',
    bloom: 'ANALYZE',
    stem: 'In the LRU page replacement algorithm, which page is evicted on a page fault?',
    reference: 'Silberschatz, Operating System Concepts, 10th Ed.',
    irtA: 1.05, irtB: 0.2, irtC: 0.19,
    options: [
      { label: 'A', text: 'The page that will not be used for the longest time in the future', justification: 'That is the optimal (OPT) algorithm, which requires future knowledge.', isCorrect: false },
      { label: 'B', text: 'The page that has not been used for the longest time in the past', justification: 'LRU (Least Recently Used) evicts the page whose most recent access is furthest in the past.', isCorrect: true },
      { label: 'C', text: 'The page that was loaded first into memory', justification: 'That is the FIFO algorithm, not LRU.', isCorrect: false },
      { label: 'D', text: 'A randomly selected page', justification: 'That is the random replacement algorithm, not LRU.', isCorrect: false },
    ],
  },

  // ─── CSC373: Algorithm Design & Analysis (Winter 2025) ────────────────────────
  {
    moduleKey: 'CSC373_Winter 2025::Greedy & Divide-and-Conquer',
    externalQuestionId: 'CSC373-GD-001',
    bloom: 'REMEMBER',
    stem: 'What is the time complexity of merge sort in the worst case?',
    reference: 'Kleinberg & Tardos, Algorithm Design, Ch. 5',
    irtA: 0.82, irtB: -0.9, irtC: 0.22,
    options: [
      { label: 'A', text: 'O(n²)', justification: 'O(n²) is the worst-case for bubble/insertion/selection sort, not merge sort.', isCorrect: false },
      { label: 'B', text: 'O(n log n)', justification: 'Merge sort divides the array in half at each level (log n levels) and merges in O(n) per level: T(n) = 2T(n/2) + O(n) → O(n log n).', isCorrect: true },
      { label: 'C', text: 'O(n)', justification: 'O(n) linear sort requires special conditions (e.g., counting sort); general comparison sort cannot do better than O(n log n).', isCorrect: false },
      { label: 'D', text: 'O(log n)', justification: 'O(log n) describes binary search, not a sorting algorithm.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC373_Winter 2025::Greedy & Divide-and-Conquer',
    externalQuestionId: 'CSC373-GD-002',
    bloom: 'UNDERSTAND',
    stem: 'A greedy algorithm makes locally optimal choices at each step. When does this guarantee a globally optimal solution?',
    reference: 'Kleinberg & Tardos, Algorithm Design, Ch. 4',
    irtA: 1.15, irtB: 0.3, irtC: 0.19,
    options: [
      { label: 'A', text: 'Always — greedy algorithms always find the global optimum', justification: 'Greedy algorithms only guarantee optimality when the problem exhibits the greedy-choice property and optimal substructure.', isCorrect: false },
      { label: 'B', text: 'When the problem exhibits the greedy-choice property and optimal substructure', justification: 'If locally optimal choices lead to a globally optimal solution (greedy-choice property) and subproblems are independent (optimal substructure), greedy works.', isCorrect: true },
      { label: 'C', text: 'Never — greedy algorithms only give approximate solutions', justification: 'Many problems (interval scheduling, Huffman coding, Dijkstra) are solved optimally by greedy algorithms.', isCorrect: false },
      { label: 'D', text: 'Only when the input is already sorted', justification: 'Sorted input is sometimes required for efficiency but is not the condition for correctness of greedy algorithms.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC373_Winter 2025::Dynamic Programming & NP-Completeness',
    externalQuestionId: 'CSC373-DP-001',
    bloom: 'UNDERSTAND',
    stem: 'What is the key difference between memoization and bottom-up dynamic programming?',
    reference: 'Kleinberg & Tardos, Algorithm Design, Ch. 6',
    irtA: 1.05, irtB: 0.1, irtC: 0.20,
    options: [
      { label: 'A', text: 'Memoization uses iteration; bottom-up uses recursion', justification: 'This is reversed: memoization uses recursion with caching; bottom-up uses iteration.', isCorrect: false },
      { label: 'B', text: 'Memoization is top-down (recursive + cache); bottom-up iteratively fills a table from smaller subproblems', justification: 'Both avoid redundant computation, but memoization caches recursive calls while bottom-up systematically solves subproblems in order.', isCorrect: true },
      { label: 'C', text: 'Bottom-up always uses more memory than memoization', justification: 'Bottom-up often uses less memory because only necessary table entries are stored; memoization may cache more.', isCorrect: false },
      { label: 'D', text: 'They produce different results for the same problem', justification: 'Both compute the same result; they differ only in implementation style.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC373_Winter 2025::Dynamic Programming & NP-Completeness',
    externalQuestionId: 'CSC373-DP-002',
    bloom: 'REMEMBER',
    stem: 'If problem A is NP-complete and A reduces to problem B in polynomial time, what can we conclude about B?',
    reference: 'Kleinberg & Tardos, Algorithm Design, Ch. 8',
    irtA: 1.20, irtB: 0.5, irtC: 0.19,
    options: [
      { label: 'A', text: 'B is in P', justification: 'We cannot conclude B is in P; the reduction shows B is at least as hard as A.', isCorrect: false },
      { label: 'B', text: 'B is NP-hard (at least as hard as any NP problem)', justification: 'If an NP-complete problem reduces to B, then B is NP-hard: solving B efficiently would solve all NP problems efficiently.', isCorrect: true },
      { label: 'C', text: 'B is easier than A', justification: 'A polynomial reduction from A to B means B is at least as hard as A, not easier.', isCorrect: false },
      { label: 'D', text: 'Nothing can be concluded about B', justification: 'The reduction implies B is NP-hard; definite conclusions can be drawn.', isCorrect: false },
    ],
  },

  // ─── CSC358: Computer Networks (Fall 2024) ────────────────────────────────────
  {
    moduleKey: 'CSC358_Fall 2024::Network Layers & Protocols',
    externalQuestionId: 'CSC358-NL-001',
    bloom: 'REMEMBER',
    stem: 'Which layer of the OSI model is responsible for end-to-end logical addressing (IP addresses)?',
    reference: 'Kurose & Ross, Computer Networking, 8th Ed.',
    irtA: 0.80, irtB: -1.0, irtC: 0.22,
    options: [
      { label: 'A', text: 'Data Link Layer (Layer 2)', justification: 'Layer 2 uses MAC addresses for local (LAN) addressing.', isCorrect: false },
      { label: 'B', text: 'Network Layer (Layer 3)', justification: 'The Network Layer (e.g., IP protocol) handles logical addressing and routing between networks.', isCorrect: true },
      { label: 'C', text: 'Transport Layer (Layer 4)', justification: 'The Transport Layer handles end-to-end communication (ports, reliability); IP addressing is Layer 3.', isCorrect: false },
      { label: 'D', text: 'Application Layer (Layer 7)', justification: 'The Application Layer handles protocols like HTTP, DNS; IP addressing is handled at Layer 3.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC358_Fall 2024::Network Layers & Protocols',
    externalQuestionId: 'CSC358-NL-002',
    bloom: 'UNDERSTAND',
    stem: 'What does ARP (Address Resolution Protocol) do?',
    reference: 'Kurose & Ross, Computer Networking, 8th Ed.',
    irtA: 0.95, irtB: -0.3, irtC: 0.20,
    options: [
      { label: 'A', text: 'Translates domain names to IP addresses', justification: 'That is DNS, not ARP.', isCorrect: false },
      { label: 'B', text: 'Maps an IP address to the corresponding MAC address on a local network', justification: 'ARP broadcasts a request for the MAC address associated with a given IP address on the local subnet.', isCorrect: true },
      { label: 'C', text: 'Assigns IP addresses dynamically to hosts', justification: 'That is DHCP, not ARP.', isCorrect: false },
      { label: 'D', text: 'Encrypts packets for secure transmission', justification: 'Encryption is handled by TLS/IPsec, not ARP.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC358_Fall 2024::Transport & Application Layer',
    externalQuestionId: 'CSC358-TA-001',
    bloom: 'UNDERSTAND',
    stem: 'What is the purpose of the TCP three-way handshake?',
    reference: 'Kurose & Ross, Computer Networking, 8th Ed.',
    irtA: 0.98, irtB: -0.4, irtC: 0.20,
    options: [
      { label: 'A', text: 'To encrypt the connection before data transfer', justification: 'The TCP handshake establishes a connection; encryption is handled by TLS on top of TCP.', isCorrect: false },
      { label: 'B', text: 'To establish a reliable connection by synchronizing sequence numbers between client and server', justification: 'SYN → SYN-ACK → ACK synchronizes initial sequence numbers, confirming both sides can send and receive before data transfer.', isCorrect: true },
      { label: 'C', text: 'To negotiate the maximum transmission unit (MTU)', justification: 'MTU is negotiated via path MTU discovery, not the TCP handshake.', isCorrect: false },
      { label: 'D', text: 'To authenticate the identities of client and server', justification: 'Authentication is performed by higher-layer protocols like TLS; the TCP handshake only establishes connectivity.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'CSC358_Fall 2024::Transport & Application Layer',
    externalQuestionId: 'CSC358-TA-002',
    bloom: 'REMEMBER',
    stem: 'Which transport layer protocol provides connectionless, low-overhead communication without guaranteed delivery?',
    reference: 'Kurose & Ross, Computer Networking, 8th Ed.',
    irtA: 0.75, irtB: -1.1, irtC: 0.22,
    options: [
      { label: 'A', text: 'TCP', justification: 'TCP is connection-oriented and provides reliable, ordered delivery.', isCorrect: false },
      { label: 'B', text: 'UDP', justification: 'UDP sends datagrams without connection setup, acknowledgment, or ordering — useful for low-latency applications like DNS and streaming.', isCorrect: true },
      { label: 'C', text: 'HTTP', justification: 'HTTP is an application layer protocol; it runs on top of TCP.', isCorrect: false },
      { label: 'D', text: 'IP', justification: 'IP is a network layer protocol, not a transport layer protocol.', isCorrect: false },
    ],
  },

  // ─── MAT137: Calculus with Proofs (Winter 2025) ───────────────────────────────
  {
    moduleKey: 'MAT137_Winter 2025::Limits & Continuity',
    externalQuestionId: 'MAT137-LC-001',
    bloom: 'REMEMBER',
    stem: 'What does it mean for a function f to be continuous at a point x = a?',
    reference: 'Spivak, Calculus, 4th Ed., Ch. 5',
    irtA: 0.82, irtB: -0.9, irtC: 0.21,
    options: [
      { label: 'A', text: 'f(a) exists but lim f(x) as x→a may not exist', justification: 'Continuity requires both f(a) and the limit to exist and be equal.', isCorrect: false },
      { label: 'B', text: 'lim(x→a) f(x) = f(a) (the limit exists, f(a) is defined, and they are equal)', justification: 'Continuity at a requires: (1) f(a) defined, (2) lim exists, (3) limit equals f(a).', isCorrect: true },
      { label: 'C', text: 'f(x) is differentiable at x = a', justification: 'Differentiability implies continuity, but continuity does not require differentiability.', isCorrect: false },
      { label: 'D', text: 'f is continuous everywhere in its domain', justification: 'Continuity at a point is a local property; it does not require continuity everywhere.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'MAT137_Winter 2025::Limits & Continuity',
    externalQuestionId: 'MAT137-LC-002',
    bloom: 'APPLY',
    stem: 'What does the Intermediate Value Theorem guarantee for a continuous function f on [a, b] with f(a) < 0 < f(b)?',
    reference: 'Spivak, Calculus, 4th Ed., Ch. 7',
    irtA: 1.10, irtB: 0.2, irtC: 0.19,
    options: [
      { label: 'A', text: 'f has a minimum at x = a', justification: 'IVT guarantees a zero exists; it says nothing about minima.', isCorrect: false },
      { label: 'B', text: 'There exists some c in (a, b) where f(c) = 0', justification: 'IVT: if f is continuous on [a,b] and f(a) and f(b) have opposite signs, there must be a root in (a,b).', isCorrect: true },
      { label: 'C', text: 'f is differentiable on (a, b)', justification: 'IVT only requires continuity; differentiability is a separate (stronger) property.', isCorrect: false },
      { label: 'D', text: 'f is monotonically increasing on [a, b]', justification: 'IVT says nothing about monotonicity; a continuous function can have many local extrema.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'MAT137_Winter 2025::Differentiation & Integration',
    externalQuestionId: 'MAT137-DI-001',
    bloom: 'APPLY',
    stem: 'What is the derivative of f(x) = x³ + 4x² − 2x + 7?',
    reference: 'Spivak, Calculus, 4th Ed., Ch. 10',
    irtA: 0.88, irtB: -0.6, irtC: 0.21,
    options: [
      { label: 'A', text: 'x² + 8x − 2', justification: 'The derivative of x³ is 3x², not x².', isCorrect: false },
      { label: 'B', text: '3x² + 8x − 2', justification: "By the power rule: d/dx(x³)=3x², d/dx(4x²)=8x, d/dx(-2x)=-2, d/dx(7)=0.", isCorrect: true },
      { label: 'C', text: '3x² + 8x − 2 + 7', justification: 'The constant 7 differentiates to 0, not 7.', isCorrect: false },
      { label: 'D', text: '3x² + 4x − 2', justification: 'The derivative of 4x² is 8x (not 4x); the coefficient doubles.', isCorrect: false },
    ],
  },
  {
    moduleKey: 'MAT137_Winter 2025::Differentiation & Integration',
    externalQuestionId: 'MAT137-DI-002',
    bloom: 'UNDERSTAND',
    stem: 'What does the Fundamental Theorem of Calculus (Part 2) state?',
    reference: 'Spivak, Calculus, 4th Ed., Ch. 14',
    irtA: 1.05, irtB: 0.0, irtC: 0.20,
    options: [
      { label: 'A', text: 'Every continuous function has an antiderivative', justification: 'That is Part 1 of FTC; Part 2 connects definite integrals to antiderivatives.', isCorrect: false },
      { label: 'B', text: 'If F is an antiderivative of f on [a,b], then ∫ₐᵇ f(x)dx = F(b) − F(a)', justification: 'FTC Part 2 allows evaluation of definite integrals using any antiderivative: subtract boundary values.', isCorrect: true },
      { label: 'C', text: 'The derivative of ∫ₐˣ f(t)dt equals f(x)', justification: "That is FTC Part 1, which connects the integral to differentiation.", isCorrect: false },
      { label: 'D', text: 'Every differentiable function is integrable', justification: 'While true, this is not what FTC Part 2 states.', isCorrect: false },
    ],
  },
]
